build-job:
  stage: build
  tags:
    - windows
    - unreal
  script:
    - $UE4_VERSION = ue4-cli-rs --getrootdir
    - pwd
    - ls
    - ./build_script.ps1

  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  cache:
    key: build-cache
    paths:
      - Saved\StagedBuilds\Windows

deploy-manually:
  stage: deploy
  when: manual
  tags:
    - windows
    - unreal
  script:
    - ls
    - Compress-Archive -Path Saved\StageBuilds\Windows  DigitalTwin.zip
    #- iscc digitaltwin.iss
  artifacts:
    paths:
      - Saved\StagedBuilds\Windows
    expire_in: 10 days
  cache:
    key: build-cache
    paths:
      - Saved\StagedBuilds\Windows
