/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
#pragma once

#include "SwaggerBaseModel.h"
#include "SwaggerNotes.h"

namespace Swagger 
{

/*
 * SwaggerDestination
 *
 * 
 */
class VASTTRAFIK_API SwaggerDestination : public Model
{
public:
    virtual ~SwaggerDestination() {}
	bool FromJson(const TSharedPtr<FJsonObject>& JsonObject) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* Route index of a stop/station. Can be used as a reference of the stop/station in a journeyDetail response */
	TOptional<FString> RouteIdx;
	FString Value;
	/* Will be set to true if departure/arrival at this stop is cancelled */
	TOptional<bool> Cancelled;
	/* Track information, if available */
	TOptional<FString> Track;
	/* Realtime track information, if available */
	TOptional<FString> RtTrack;
	/* The attribute type specifies the type of location. Valid values are ST (stop/station), ADR (address) or POI (point of interest) */
	FString Type;
	/* Date in format YYYY-MM-DD */
	FDateTime Date = FDateTime(0);
	TOptional<SwaggerNotes> Notes;
	/* ID of this stop */
	FString Id;
	/* Realtime date in format YYYY-MM-DD, if available */
	TOptional<FDateTime> RtDate;
	/* Time in format HH:MM */
	FString Time;
	/* Date in format YYYY-MM-DD.  Based on the direct travel time */
	TOptional<FDateTime> Directdate;
	/* Contains the name of the location */
	FString Name;
	/* Realtime time in format HH:MM if available */
	TOptional<FString> RtTime;
	/* Direct Time format HH:MM. Based on the direct travel time */
	TOptional<FString> Directtime;
};

}
