/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
#pragma once

#include "SwaggerBaseModel.h"
#include "SwaggerSysteminfoApi.h"

#include "SwaggerSystemInfo.h"

namespace Swagger 
{

/* Provides information about the journey planner and the underlying data
 *
 * Provides information about the journey planner and underlying data. It will return the begin of end of the timetable period and the creation date of the timetable data.
*/
class VASTTRAFIK_API SwaggerSysteminfoApi::GetSystemInfoRequest : public Request
{
public:
    virtual ~GetSystemInfoRequest() {}
	void SetupHttpRequest(const TSharedRef<IHttpRequest, ESPMode::ThreadSafe>& HttpRequest) const final;
	FString ComputePath() const final;
    
	/* the required response format */
	TOptional<FString> Format;
	/* If JSONP response format is needed, you can append an additional parameter to specify the name of a callback function, and the JSON object will be wrapped by a function call with this name. */
	TOptional<FString> JsonpCallback;
};

class VASTTRAFIK_API SwaggerSysteminfoApi::GetSystemInfoResponse : public Response
{
public:
    virtual ~GetSystemInfoResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonObject) final;
    
    SwaggerSystemInfo Content;
};

}
