/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
#pragma once

#include "SwaggerBaseModel.h"
#include "SwaggerTimeTableData.h"
#include "SwaggerTimeTablePeriod.h"

namespace Swagger 
{

/*
 * SwaggerTimetableInfo
 *
 * 
 */
class VASTTRAFIK_API SwaggerTimetableInfo : public Model
{
public:
    virtual ~SwaggerTimetableInfo() {}
	bool FromJson(const TSharedPtr<FJsonObject>& JsonObject) final;
	void WriteJson(JsonWriter& Writer) const final;

	SwaggerTimeTableData TimeTableData;
	SwaggerTimeTablePeriod TimeTablePeriod;
};

}
