/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
#pragma once

#include "SwaggerBaseModel.h"
#include "SwaggerLivemapApi.h"

#include "SwaggerLiveMap.h"

namespace Swagger 
{

/* Returns the positions of all vehicles in a given bounding box
 *
 * This method will return the positions of all vehicles in a given bounding box.
*/
class VASTTRAFIK_API SwaggerLivemapApi::LivemapRequest : public Request
{
public:
    virtual ~LivemapRequest() {}
	void SetupHttpRequest(const TSharedRef<IHttpRequest, ESPMode::ThreadSafe>& HttpRequest) const final;
	FString ComputePath() const final;
    
	/* Left border (longitude) of the bounding box in WGS84 * 1000000 */
	FString Minx;
	/* Right border (longitude) of the bounding box in WGS84 * 1000000 */
	FString Maxx;
	/* Lower border (latitude) of the bounding box in WGS84 * 1000000 */
	FString Miny;
	/* Upper border (latitude) of the bounding box in WGS84 * 1000000 */
	FString Maxy;
	enum class OnlyRealtimeEnum
	{
		Yes,
		No,
  	};
	/* Can be used to define whether all vehicles should be returned or only those  vehicles which have realtime information. If it is set to yes, only vehicles  with realtime information are returned, if it is set to no, all vehicles in the  bounding box are returned. */
	OnlyRealtimeEnum OnlyRealtime;
};

class VASTTRAFIK_API SwaggerLivemapApi::LivemapResponse : public Response
{
public:
    virtual ~LivemapResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonObject) final;
    
    SwaggerLiveMap Content;
};

}
