/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
#pragma once

#include "SwaggerBaseModel.h"
#include "SwaggerCoordLocation.h"
#include "SwaggerStopLocation.h"

namespace Swagger 
{

/*
 * SwaggerLocationList
 *
 * 
 */
class VASTTRAFIK_API SwaggerLocationList : public Model
{
public:
    virtual ~SwaggerLocationList() {}
	bool FromJson(const TSharedPtr<FJsonObject>& JsonObject) final;
	void WriteJson(JsonWriter& Writer) const final;

	TOptional<FString> ErrorText;
	TOptional<FString> Error;
	TOptional<FDateTime> Serverdate;
	/* Current server time in format HH:MM */
	TOptional<FString> Servertime;
	TOptional<TArray<SwaggerStopLocation>> StopLocation;
	TOptional<TArray<SwaggerCoordLocation>> CoordLocation;
	FString NoNamespaceSchemaLocation;
};

}
