/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
#pragma once

#include "CoreMinimal.h"
#include "SwaggerBaseModel.h"

namespace Swagger 
{

class VASTTRAFIK_API SwaggerArrivalBoardApi
{
public:
	SwaggerArrivalBoardApi();
	~SwaggerArrivalBoardApi();

	void SetURL(const FString& Url);
	void AddHeaderParam(const FString& Key, const FString& Value);
	void ClearHeaderParams();

	class GetArrivalBoardRequest;
	class GetArrivalBoardResponse;
	
    DECLARE_DELEGATE_OneParam(FGetArrivalBoardDelegate, const GetArrivalBoardResponse&);
    
    bool GetArrivalBoard(const GetArrivalBoardRequest& Request, const FGetArrivalBoardDelegate& Delegate = FGetArrivalBoardDelegate()) const;
    
private:
    void OnGetArrivalBoardResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FGetArrivalBoardDelegate Delegate) const;
    
	bool IsValid() const;
	void HandleResponse(FHttpResponsePtr HttpResponse, bool bSucceeded, Response& InOutResponse) const;

	FString Url;
	TMap<FString,FString> AdditionalHeaderParams;
};
	
}
