/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
#pragma once

#include "SwaggerBaseModel.h"

namespace Swagger 
{

/*
 * SwaggerDateBegin
 *
 * 
 */
class VASTTRAFIK_API SwaggerDateBegin : public Model
{
public:
    virtual ~SwaggerDateBegin() {}
	bool FromJson(const TSharedPtr<FJsonObject>& JsonObject) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* Begin of timetable period in format YYYY-MM-DD */
	FDateTime Value = FDateTime(0);
};

}
