/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
#pragma once

#include "SwaggerBaseModel.h"
#include "SwaggerTripApi.h"

#include "SwaggerTripList.h"

namespace Swagger 
{

/* Calculates a trip from a specified origin to a specified destination.
 *
 * Calculates a trip from a specified origin to a specified destination. These might be stop/station IDs or coordinates based on addresses and points of interest validated by the location service or coordinates freely defined by the client. Parameters specifying both origin and destination are mandatory in calls to the trip service. When specifying a stop as origin, the parameter originId is used, while originCoordLat, originCoordLong, and originCoordName are used to specify a (named) coordinate. For the destination, the corresponding parameters are named either destId or destCoordLat, destCoordLong and destCoordName. It is also possible to define a via-stop/station. This forces the journey planner to search for trips which pass the defined station. The parameter is called viaId. When searching for a trip that goes via a coordinate, rather than a stop, two separate trip requests need to be combined into one.
*/
class VASTTRAFIK_API SwaggerTripApi::GetTripRequest : public Request
{
public:
    virtual ~GetTripRequest() {}
	void SetupHttpRequest(const TSharedRef<IHttpRequest, ESPMode::ThreadSafe>& HttpRequest) const final;
	FString ComputePath() const final;
    
	/* origin stop id */
	TOptional<int64> OriginId;
	/* origin latitude of center coordinate in the WGS84 system */
	TOptional<double> OriginCoordLat;
	/* origin longitude of center coordinate in the WGS84 system */
	TOptional<double> OriginCoordLong;
	/* name of the address at the specified origin coordinate */
	TOptional<FString> OriginCoordName;
	/* destination stop id */
	TOptional<int64> DestId;
	/* destination latitude of center coordinate in the WGS84 system */
	TOptional<double> DestCoordLat;
	/* destination longitude of center coordinate in the WGS84 system */
	TOptional<double> DestCoordLong;
	/* name of the address at the specified destination coordinate */
	TOptional<FString> DestCoordName;
	/* via stop/station id */
	TOptional<int64> ViaId;
	/* date of the trip */
	TOptional<FDateTime> Date;
	/* time of the trip in format HH:MM */
	TOptional<FString> Time;
	/* to specify that the given time and date is not the departure time but the latest time to arrive at the destination, set this parameter to the value 1. */
	TOptional<FString> SearchForArrival;
	/* to exclude trips with Västtågen, set this parameter to 0. */
	TOptional<FString> UseVas;
	/* to exclude trips with long distance trains, set this parameter to 0. */
	TOptional<FString> UseLDTrain;
	/* to exclude trips with regional trains, set this parameter to 0. */
	TOptional<FString> UseRegTrain;
	/* to exclude trips with buses, set this parameter to 0. */
	TOptional<FString> UseBus;
	/* to include medical transport lines trips with buses, set this parameter to 1. */
	TOptional<FString> UseMedical;
	/* to search for medical transport connections from the origin, set this parameter to 1. */
	TOptional<FString> OriginMedicalCon;
	/* to search for medical transport connections from the destination, set this parameter to 1. */
	TOptional<FString> DestMedicalCon;
	/* to search for trips where at least one wheelchair space is present in the vehicle, set this parameter to 1. */
	TOptional<FString> WheelChairSpace;
	/* to search for trips with space for stroller, baby carriage or rollator in the vehicle, set this parameter to 1. */
	TOptional<FString> StrollerSpace;
	/* to search for trips where the vehicle is equipped with a low floor section, but not necessarily a ramp or lift, set this parameter to 1. */
	TOptional<FString> LowFloor;
	/* to search for trips where the vehicle is equipped with ramp or lift that allows fully barrier-free boarding and alighting, set this parameter to 1. */
	TOptional<FString> RampOrLift;
	/* to exclude trips with boats, set this parameter to 0. */
	TOptional<FString> UseBoat;
	/* to exclude trips with trams, set this parameter to 0. */
	TOptional<FString> UseTram;
	/* to exclude trips with public transportation, set this parameter to 0. */
	TOptional<FString> UsePT;
	/* to exclude journeys which require tel. registration, set this parameter to 1. */
	TOptional<FString> ExcludeDR;
	/* maximum walking distance from/to the coordinate in meters */
	TOptional<int32> MaxWalkDist;
	/* walking speed given in percent of normal speed */
	TOptional<FString> WalkSpeed;
	/* to exclude trips with walks from/to coordinates, set this to 0 */
	TOptional<FString> OriginWalk;
	/* to exclude trips with walks from/to coordinates, set this to 0 */
	TOptional<FString> DestWalk;
	/* to search for walk-only trips, set this to 1 */
	TOptional<FString> OnlyWalk;
	/* to search for trips with a bike ride from the origin to a nearby stop, where the journey continues using public transport, set this to 1. */
	TOptional<FString> OriginBike;
	/* maximum biking distance from/to the coordinate in meters */
	TOptional<int32> MaxBikeDist;
	/* optimize for either the fastest route or a route that is made up of a larger percentage of bike road, where 'F' is used to indicate tha fastest route with mimimized travel time, and 'D' is used to indicate dedicated bike roads to maximize use of bike roads. */
	TOptional<FString> BikeCriterion;
	/* determines the altitude profile of the route, based on a setting for how fast the user can bike when it is steep, where 'E' is used to indicate easy with minimized steepnes, 'N' is used to indicate normal, and 'P' is used to indicate powerful to allow more steepness. */
	TOptional<FString> BikeProfile;
	/* to search for bike-only trips, set this to 1 */
	TOptional<FString> OnlyBike;
	/* to search for trips where customer travels by car from the origin and is dropped off at a stop to continue the trip using public transport, set this to 1. */
	TOptional<FString> OriginCar;
	/* to search for trips where the customer travels by car from the origin, parks at a commuter parking and walks to a nearby stop to continue the trip using public transport, set this to 1. */
	TOptional<FString> OriginCarWithParking;
	/* maximum car distance from/to the coordinate in meters */
	TOptional<int32> MaxCarDist;
	/* to search for car-only trips, set this to 1 */
	TOptional<FString> OnlyCar;
	/* maximum number of changes in the trip */
	TOptional<int32> MaxChanges;
	/* to prolong the minimal change times in minutes between the public transport legs of the returned journeys */
	TOptional<int32> AdditionalChangeTime;
	/* to ignore the default change margin, set this to 1 */
	TOptional<FString> DisregardDefaultChangeMargin;
	/* if the reference URL for the journey detail service is not needed in the re, set this to 0 */
	TOptional<FString> NeedJourneyDetail;
	/* if a reference link for each leg of the resulting trips, which can be used to request the geometry, is needed, set this to 1 */
	TOptional<FString> NeedGeo;
	/* if a reference link for each leg of the resulting trips, which can be used to request the itinerary, is needed, set this to 1 */
	TOptional<FString> NeedItinerary;
	/* the number of trips in the returned result */
	TOptional<int32> NumTrips;
	/* the required response format */
	TOptional<FString> Format;
	/* If JSONP response format is needed, you can append an additional parameter to specify the name of a callback function, and the JSON object will be wrapped by a function call with this name. */
	TOptional<FString> JsonpCallback;
};

class VASTTRAFIK_API SwaggerTripApi::GetTripResponse : public Response
{
public:
    virtual ~GetTripResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonObject) final;
    
    SwaggerTripList Content;
};

}
