/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
#pragma once

#include "SwaggerBaseModel.h"
#include "SwaggerDateBegin.h"
#include "SwaggerDateEnd.h"

namespace Swagger 
{

/*
 * SwaggerTimeTablePeriod
 *
 * 
 */
class VASTTRAFIK_API SwaggerTimeTablePeriod : public Model
{
public:
    virtual ~SwaggerTimeTablePeriod() {}
	bool FromJson(const TSharedPtr<FJsonObject>& JsonObject) final;
	void WriteJson(JsonWriter& Writer) const final;

	SwaggerDateBegin DateBegin;
	SwaggerDateEnd DateEnd;
};

}
