/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 * NOTE: Mikpe has edited this class, since it was not reflecting the data västtrafik sends
 */
#pragma once

#include "SwaggerBaseModel.h"

namespace Swagger
{

  enum class VehicleType
  {
    Vas,
    Ldt,
    Reg,
    Bus,
    Boat,
    Tram,
    Taxi,
    Unknown,
  };

  /*
   * SwaggerVehicle
   *
   *
   */
  class VASTTRAFIK_API SwaggerVehicle : public Model
  {
  public:
    virtual ~SwaggerVehicle() {}
    bool FromJson(const TSharedPtr<FJsonObject>& JsonObject) final;
    void WriteJson(JsonWriter& Writer) const final;

    /* Line color of the journey */
    FString Lcolor;
    /* Product class */
    VehicleType ProdClass;
    /* Background color of the journey */
    FString Bcolor;
    /* Direction of the vehicle. This is a value between 0 and 31 which is describing a direction vector */
    int32 Direction = 0;
    /* Journey name */
    FString Name;
    /* Service GID */
    FString Gid;
    /* Current delay of the vehicle in minutes, can be negative, zero or positive */
    int32 Delay = 0;
    /* Y coordinate (latitude) of the position in WGS84 */
    double Y = 0.0;
    /* X coordinate (longitude) of the position in WGS84 */
    double X = 0.0;
  };

}
