/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
#pragma once

#include "SwaggerBaseModel.h"

namespace Swagger 
{

/*
 * SwaggerStopLocation
 *
 * 
 */
class VASTTRAFIK_API SwaggerStopLocation : public Model
{
public:
    virtual ~SwaggerStopLocation() {}
	bool FromJson(const TSharedPtr<FJsonObject>& JsonObject) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* This ID can either be used as originId or destId to perform a trip request or to call a departure  board */
	FString Id;
	/* The WGS84 longitude */
	FString Lon;
	/* This index can be used to reorder the StopLocations and CoordLocations in JSON format response to their correct order. IN JSON you can receive two arrays, one for Stops and one for Addresses. This attribute is only contained in reponses to the location.name request. The location with idx=1 is the best fitting location */
	FString Idx;
	/* This value specifies some kind of importance of this stop. The more traffic at this stop the higher the weight. The range is between 0 and 32767. This attribute is just contained in the location.allstops response */
	TOptional<FString> Weight;
	/* Contains the output name of this stop or station */
	FString Name;
	/* Track information, if available */
	TOptional<FString> Track;
	/* The WGS84 latitude */
	FString Lat;
};

}
