/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
#pragma once

#include "SwaggerBaseModel.h"

namespace Swagger 
{

/*
 * SwaggerNote
 *
 * 
 */
class VASTTRAFIK_API SwaggerNote : public Model
{
public:
    virtual ~SwaggerNote() {}
	bool FromJson(const TSharedPtr<FJsonObject>& JsonObject) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* Priority of the note which can be used to order the notes in the list. */
	FString Priority;
	enum class SeverityEnum
	{
		High,
		Normal,
		Low,
  	};
	/* Severity of this note, can be high, normal or low */
	SeverityEnum Severity;
	/* Type of this note */
	TOptional<FString> Key;
};

}
