/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
#pragma once

#include "SwaggerBaseModel.h"
#include "SwaggerJourneyDetailRef.h"

namespace Swagger 
{

/*
 * SwaggerDeparture
 *
 * 
 */
class VASTTRAFIK_API SwaggerDeparture : public Model
{
public:
    virtual ~SwaggerDeparture() {}
	bool FromJson(const TSharedPtr<FJsonObject>& JsonObject) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* Foregroundcolor of this line */
	FString FgColor;
	/* Contains the name of the stop/station */
	FString Stop;
	/* Will be true if this journey needs to be booked */
	TOptional<bool> Booking;
	/* Direction information */
	FString Direction;
	SwaggerJourneyDetailRef JourneyDetailRef;
	/* Track information, if available */
	FString Track;
	/* Realtime track information, if available */
	TOptional<FString> RtTrack;
	/* Short name of the leg */
	FString Sname;
	/* The attribute type specifies the type of the departing journey. Valid values are VAS, LDT (Long Distance Train), REG (Regional train), BUS , BOAT, TRAM, TAXI (Taxi/Telebus) */
	FString Type;
	/* Date in format YYYY-MM-DD */
	FDateTime Date = FDateTime(0);
	/* Backgroundcolor of this line */
	FString BgColor;
	/* Stroke style of this line */
	FString Stroke;
	/* Realtime date in format YYYY-MM-DD, if available */
	FDateTime RtDate = FDateTime(0);
	/* Time in format HH:MM */
	FString Time;
	/* The attribute name specifies the name of the departing journey */
	FString Name;
	/* Realtime time in format HH:MM if available */
	FString RtTime;
	/* Will be true if this journey is a night journey */
	TOptional<bool> Night;
	/* Contains the id of the stop/station */
	FString Stopid;
	/* Contains the id of the journey */
	FString Journeyid;
	enum class AccessibilityEnum
	{
		WheelChair,
		LowFloor,
  	};
	/* will only be set if the vehicle has wheelchair + ramp/lift or lowfloor according to realtime data */
	AccessibilityEnum Accessibility;
};

}
