/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
#pragma once

#include "SwaggerBaseModel.h"
#include "SwaggerVehicle.h"

namespace Swagger 
{

/*
 * SwaggerLiveMap
 *
 * 
 */
class VASTTRAFIK_API SwaggerLiveMap : public Model
{
public:
    virtual ~SwaggerLiveMap() {}
	bool FromJson(const TSharedPtr<FJsonObject>& JsonObject) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* Current server time */
	FDateTime Time = FDateTime(0);
	/* Right border (longitude) of the bounding box in WGS84 * 1000000 */
	double Maxx = 0.0;
	/* Upper border (latitude) of the bounding box in WGS84 * 1000000 */
	double Maxy = 0.0;
	TArray<SwaggerVehicle> Vehicles;
	/* Left border (longitude) of the bounding box in WGS84 * 1000000 */
	double Minx = 0.0;
	/* Lower border (latitude) of the bounding box in WGS84 * 1000000 */
	double Miny = 0.0;
};

}
