/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
#pragma once

#include "SwaggerBaseModel.h"

namespace Swagger 
{

/*
 * SwaggerStop
 *
 * 
 */
class VASTTRAFIK_API SwaggerStop : public Model
{
public:
    virtual ~SwaggerStop() {}
	bool FromJson(const TSharedPtr<FJsonObject>& JsonObject) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* Route index of a stop/station. Can be used as a reference of the stop/station in a journeyDetail response */
	FString RouteIdx;
	/* Arrival date in format YYYY-MM-DD, if available */
	TOptional<FDateTime> ArrDate;
	/* Departure time in format HH:MM, if available */
	TOptional<FString> DepTime;
	/* The WGS84 longitude */
	FString Lon;
	/* Departure date in format YYYY-MM-DD, if available */
	TOptional<FDateTime> DepDate;
	/* Track information, if available */
	FString Track;
	/* Realtime track information, if available */
	TOptional<FString> RtTrack;
	FString Id;
	/* Realtime departure time in format HH:MM if available */
	TOptional<FString> RtDepTime;
	/* Realtime arrival time in format HH:MM if available */
	TOptional<FString> RtArrTime;
	/* Contains the name of the stop/station */
	FString Name;
	/* Arrival time in format HH:MM, if available */
	TOptional<FString> ArrTime;
	/* The WGS84 latitude */
	FString Lat;
	/* Realtime departure date in format YYYY-MM-DD, if available */
	TOptional<FDateTime> RtDepDate;
	/* Realtime arrival date in format YYYY-MM-DD, if available */
	TOptional<FDateTime> RtArrDate;
};

}
