/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
#pragma once

#include "CoreMinimal.h"
#include "SwaggerBaseModel.h"

namespace Swagger 
{

class VASTTRAFIK_API SwaggerJourneyDetailApi
{
public:
	SwaggerJourneyDetailApi();
	~SwaggerJourneyDetailApi();

	void SetURL(const FString& Url);
	void AddHeaderParam(const FString& Key, const FString& Value);
	void ClearHeaderParams();

	class GetJourneyDetailRequest;
	class GetJourneyDetailResponse;
	
    DECLARE_DELEGATE_OneParam(FGetJourneyDetailDelegate, const GetJourneyDetailResponse&);
    
    bool GetJourneyDetail(const GetJourneyDetailRequest& Request, const FGetJourneyDetailDelegate& Delegate = FGetJourneyDetailDelegate()) const;
    
private:
    void OnGetJourneyDetailResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FGetJourneyDetailDelegate Delegate) const;
    
	bool IsValid() const;
	void HandleResponse(FHttpResponsePtr HttpResponse, bool bSucceeded, Response& InOutResponse) const;

	FString Url;
	TMap<FString,FString> AdditionalHeaderParams;
};
	
}
