/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
#pragma once

#include "SwaggerBaseModel.h"
#include "SwaggerDestination.h"
#include "SwaggerGeometryRef.h"
#include "SwaggerJourneyDetailRef.h"
#include "SwaggerNotes.h"
#include "SwaggerOrigin.h"

namespace Swagger 
{

/*
 * SwaggerLeg
 *
 * 
 */
class VASTTRAFIK_API SwaggerLeg : public Model
{
public:
    virtual ~SwaggerLeg() {}
	bool FromJson(const TSharedPtr<FJsonObject>& JsonObject) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* Foregroundcolor of this line */
	TOptional<FString> FgColor;
	/* Will be true if this journey needs to be booked */
	TOptional<bool> Booking;
	/* Direction information */
	TOptional<FString> Direction;
	TOptional<SwaggerJourneyDetailRef> JourneyDetailRef;
	/* Will be true if this journey is cancelled */
	TOptional<bool> Cancelled;
	/* Energy use */
	TOptional<float> Kcal;
	TOptional<SwaggerOrigin> Origin;
	/* Short name of the leg */
	TOptional<FString> Sname;
	/* The attribute type specifies the type of the leg. Valid values are VAS, LDT (Long Distance Train), REG (Regional train), BUS , BOAT, TRAM, TAXI (Taxi/Telebus). Furthermore it can be of type WALK, BIKE and CAR if these legs are routes on the street network */
	FString Type;
	TOptional<SwaggerGeometryRef> GeometryRef;
	/* Backgroundcolor of this line */
	TOptional<FString> BgColor;
	TOptional<SwaggerNotes> Notes;
	/* ID of the journey */
	TOptional<FString> Id;
	/* Stroke style of this line */
	TOptional<FString> Stroke;
	/* Will be true if this journey is not reachable due to delay of the feeder */
	TOptional<bool> Reachable;
	/* The attribute name specifies the name of the leg */
	FString Name;
	/* Will be true if this journey is a night journey */
	TOptional<bool> Night;
	TOptional<SwaggerDestination> Destination;
	/* Percentage of the route that is made up of bike roads */
	TOptional<float> PercentBikeRoad;
	/* will only be set if the vehicle has wheelchair + ramp/lift or lowfloor according to realtime data */
	TOptional<FString> Accessibility;
};

}
