/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
#pragma once

#include "SwaggerBaseModel.h"
#include "SwaggerLeg.h"

namespace Swagger 
{

/*
 * SwaggerTrip
 *
 * 
 */
class VASTTRAFIK_API SwaggerTrip : public Model
{
public:
    virtual ~SwaggerTrip() {}
	bool FromJson(const TSharedPtr<FJsonObject>& JsonObject) final;
	void WriteJson(JsonWriter& Writer) const final;

	TOptional<TArray<SwaggerLeg>> Leg;
	/* IMPORTANT NOTE: journeys that are presented when the default change margin has been disregarded are not covered by V�sttrafiks travel warranty (Swedish: resegaranti). */
	TOptional<bool> TravelWarranty;
	/* The state indicates if the trip is still possible to ride based on the current realtime situation */
	TOptional<bool> Valid;
	/* The type indicates whether this is an original connection or an realtime alternative */
	bool Alternative = false;
	enum class TypeEnum
	{
		Walk,
		Bike,
		Car,
  	};
	/* Type of trip */
	TOptional<TypeEnum> Type;
};

}
