/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
#pragma once

#include "SwaggerBaseModel.h"
#include "SwaggerGeometryApi.h"

#include "SwaggerGeometry.h"

namespace Swagger 
{

/* Returns the polyline for a leg.
 *
 * Returns the polyline for a leg. This service can not be called directly but only by reference URLs in a result of a trip or JourneyDetail request. The result contains a list of WGS84 coordinates which can be used to display the polyline on a map.If the parameter needItinerary&#x3D;1 is passed in the URL of the trip request that contained the reference to the Geometry service, the geometry reference link will also contain an itinerary for walk, bike and car legs, that can be used to generate turn-by-turn instructions.
*/
class VASTTRAFIK_API SwaggerGeometryApi::GetGeometryRequest : public Request
{
public:
    virtual ~GetGeometryRequest() {}
	void SetupHttpRequest(const TSharedRef<IHttpRequest, ESPMode::ThreadSafe>& HttpRequest) const final;
	FString ComputePath() const final;
    
	/* the ref query parameter, URL decoded, from a URL retrieved as a result of a trip or JourneyDetail request */
	FString Ref;
};

class VASTTRAFIK_API SwaggerGeometryApi::GetGeometryResponse : public Response
{
public:
    virtual ~GetGeometryResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonObject) final;
    
    SwaggerGeometry Content;
};

}
