/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
#pragma once

#include "SwaggerBaseModel.h"

namespace Swagger 
{

/*
 * SwaggerJourneyName
 *
 * 
 */
class VASTTRAFIK_API SwaggerJourneyName : public Model
{
public:
    virtual ~SwaggerJourneyName() {}
	bool FromJson(const TSharedPtr<FJsonObject>& JsonObject) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* End of validity on total route. */
	int32 RouteIdxTo = 0;
	/* Start of validity on total route */
	int32 RouteIdxFrom = 0;
	/* Name to be displayed */
	FString Name;
};

}
