/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
#pragma once

#include "SwaggerBaseModel.h"
#include "SwaggerJourneyDetailApi.h"

#include "SwaggerJourneyDetail.h"

namespace Swagger 
{

/* Returns information about the complete route of a trip.
 *
 * Delivers information about the complete route of a trip. This service can not be called directly but only by reference URLs in a result of a trip or departureBoard request. It contains a list of all stops/stations of this journey including all departure and arrival times (with real-time data if available) and additional information like specific attributes about facilities and other texts.
*/
class VASTTRAFIK_API SwaggerJourneyDetailApi::GetJourneyDetailRequest : public Request
{
public:
    virtual ~GetJourneyDetailRequest() {}
	void SetupHttpRequest(const TSharedRef<IHttpRequest, ESPMode::ThreadSafe>& HttpRequest) const final;
	FString ComputePath() const final;
    
	/* the ref query parameter, URL decoded, from a URL retrieved as a result of a trip or or departureBoard request */
	FString Ref;
};

class VASTTRAFIK_API SwaggerJourneyDetailApi::GetJourneyDetailResponse : public Response
{
public:
    virtual ~GetJourneyDetailResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonObject) final;
    
    SwaggerJourneyDetail Content;
};

}
