/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
#pragma once

#include "SwaggerBaseModel.h"
#include "SwaggerDepartureBoardApi.h"

#include "SwaggerDepartureBoard.h"

namespace Swagger 
{

/* Return the next 20 departures (or less if not existing) from a given point in time or the next departures in a given timespan.
 *
 * This method will return the next 20 departures (or less if not existing) from a given point in time or the next departures in a given timespan. The service can only be called for stops/stations by using according ID retrieved by the location method. The parameter is called id. The time and date are defined with the parameters date and time.
*/
class VASTTRAFIK_API SwaggerDepartureBoardApi::GetDepartureBoardRequest : public Request
{
public:
    virtual ~GetDepartureBoardRequest() {}
	void SetupHttpRequest(const TSharedRef<IHttpRequest, ESPMode::ThreadSafe>& HttpRequest) const final;
	FString ComputePath() const final;
    
	/* stop id */
	int64 Id;
	/* the date */
	FDateTime Date;
	/* the time in format HH:MM */
	FString Time;
	/* to exclude trips with Västtågen, set this parameter to 0. */
	TOptional<FString> UseVas;
	/* to exclude trips with long distance trains, set this parameter to 0. */
	TOptional<FString> UseLDTrain;
	/* to exclude trips with regional trains, set this parameter to 0. */
	TOptional<FString> UseRegTrain;
	/* to exclude trips with buses, set this parameter to 0. */
	TOptional<FString> UseBus;
	/* to exclude trips with boats, set this parameter to 0. */
	TOptional<FString> UseBoat;
	/* to exclude trips with trams, set this parameter to 0. */
	TOptional<FString> UseTram;
	/* to exclude journeys which require tel. registration, set this parameter to 0. */
	TOptional<FString> ExcludeDR;
	/* to get the next departures in a specified timespan of up to 24 hours (unit: minutes). If this parameter is not set, the result will contain the next 20 departures. */
	TOptional<int32> TimeSpan;
	/* if timeSpan is set you can further reduce the number of returned journeys by adding this parameter, which will cause only the given number of journeys for every combination of line and direction. */
	TOptional<int32> MaxDeparturesPerLine;
	/* if the reference URL for the journey detail service is not needed in the result, set this parameter to 0 */
	TOptional<FString> NeedJourneyDetail;
	/* stop id in order to get only departures of vehicles with a specified direction */
	TOptional<int64> Direction;
	/* the required response format */
	TOptional<FString> Format;
	/* If JSONP response format is needed, you can append an additional parameter to specify the name of a callback function, and the JSON object will be wrapped by a function call with this name. */
	TOptional<FString> JsonpCallback;
};

class VASTTRAFIK_API SwaggerDepartureBoardApi::GetDepartureBoardResponse : public Response
{
public:
    virtual ~GetDepartureBoardResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonObject) final;
    
    SwaggerDepartureBoard Content;
};

}
