/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
#pragma once

#include "SwaggerBaseModel.h"

namespace Swagger 
{

/*
 * SwaggerJourneyType
 *
 * 
 */
class VASTTRAFIK_API SwaggerJourneyType : public Model
{
public:
    virtual ~SwaggerJourneyType() {}
	bool FromJson(const TSharedPtr<FJsonObject>& JsonObject) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* End of validity on total route. */
	int32 RouteIdxTo = 0;
	/* Start of validity on total route */
	int32 RouteIdxFrom = 0;
	/* The attribute type specifies the type of the journey. Valid values are VAS, LDT (Long Distance Train), REG (Regional train), BUS , BOAT, TRAM, TAXI (Taxi/Telebus) */
	FString Type;
};

}
