/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
#pragma once

#include "SwaggerBaseModel.h"

namespace Swagger 
{

/*
 * SwaggerJourneyDetailRef
 *
 * 
 */
class VASTTRAFIK_API SwaggerJourneyDetailRef : public Model
{
public:
    virtual ~SwaggerJourneyDetailRef() {}
	bool FromJson(const TSharedPtr<FJsonObject>& JsonObject) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* Contains a URL to call the REST interface for journey details */
	FString Ref;
};

}
