/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
#pragma once

#include "SwaggerBaseModel.h"
#include "SwaggerLocationApi.h"

#include "SwaggerLocationList.h"

namespace Swagger 
{

/* Returns a list of all stops available in the journey planner.
 *
 * Returns a list of all stops available in the journey planner. Be aware that a call of this service is very time consuming and should be only requested when it is really needed.
*/
class VASTTRAFIK_API SwaggerLocationApi::GetAllStopsRequest : public Request
{
public:
    virtual ~GetAllStopsRequest() {}
	void SetupHttpRequest(const TSharedRef<IHttpRequest, ESPMode::ThreadSafe>& HttpRequest) const final;
	FString ComputePath() const final;
    
	/* the required response format */
	TOptional<FString> Format;
	/* If JSONP response format is needed, you can append an additional parameter to specify the name of a callback function, and the JSON object will be wrapped by a function call with this name. */
	TOptional<FString> JsonpCallback;
};

class VASTTRAFIK_API SwaggerLocationApi::GetAllStopsResponse : public Response
{
public:
    virtual ~GetAllStopsResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonObject) final;
    
    SwaggerLocationList Content;
};

/* Returns a list of possible matches in the journey planner database
 *
 * Performs a pattern matching of a user input to retrieve a list of possible matches in the journey planner database. Possible matches might be stops/stations, points of interest and addresses.
*/
class VASTTRAFIK_API SwaggerLocationApi::GetLocationByNameRequest : public Request
{
public:
    virtual ~GetLocationByNameRequest() {}
	void SetupHttpRequest(const TSharedRef<IHttpRequest, ESPMode::ThreadSafe>& HttpRequest) const final;
	FString ComputePath() const final;
    
	/* a string with the user input */
	TOptional<FString> Input;
	/* the required response format */
	TOptional<FString> Format;
	/* If JSONP response format is needed, you can append an additional parameter to specify the name of a callback function, and the JSON object will be wrapped by a function call with this name. */
	TOptional<FString> JsonpCallback;
};

class VASTTRAFIK_API SwaggerLocationApi::GetLocationByNameResponse : public Response
{
public:
    virtual ~GetLocationByNameResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonObject) final;
    
    SwaggerLocationList Content;
};

/* Returns the address nearest a given coordinate.
 *
 * 
*/
class VASTTRAFIK_API SwaggerLocationApi::GetNearbyAddressRequest : public Request
{
public:
    virtual ~GetNearbyAddressRequest() {}
	void SetupHttpRequest(const TSharedRef<IHttpRequest, ESPMode::ThreadSafe>& HttpRequest) const final;
	FString ComputePath() const final;
    
	/* latitude of coordinate in the WGS84 system */
	double OriginCoordLat;
	/* longitude of coordinate in the WGS84 system */
	double OriginCoordLong;
	/* the required response format */
	TOptional<FString> Format;
	/* If JSONP response format is needed, you can append an additional parameter to specify the name of a callback function, and the JSON object will be wrapped by a function call with this name. */
	TOptional<FString> JsonpCallback;
};

class VASTTRAFIK_API SwaggerLocationApi::GetNearbyAddressResponse : public Response
{
public:
    virtual ~GetNearbyAddressResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonObject) final;
    
    SwaggerLocationList Content;
};

/* Returns a list of stops around a given center coordinate.
 *
 * Returns a list of stops around a given center coordinate. The returned results are ordered by their distance to the center coordinate.
*/
class VASTTRAFIK_API SwaggerLocationApi::GetNearbyStopsRequest : public Request
{
public:
    virtual ~GetNearbyStopsRequest() {}
	void SetupHttpRequest(const TSharedRef<IHttpRequest, ESPMode::ThreadSafe>& HttpRequest) const final;
	FString ComputePath() const final;
    
	/* latitude of center coordinate in the WGS84 system */
	double OriginCoordLat;
	/* longitude of center coordinate in the WGS84 system */
	double OriginCoordLong;
	/* maximum number of returned stops */
	TOptional<int32> MaxNo;
	/* maximum distance from the center coordinate */
	TOptional<int32> MaxDist;
	/* the required response format */
	TOptional<FString> Format;
	/* If JSONP response format is needed, you can append an additional parameter to specify the name of a callback function, and the JSON object will be wrapped by a function call with this name. */
	TOptional<FString> JsonpCallback;
};

class VASTTRAFIK_API SwaggerLocationApi::GetNearbyStopsResponse : public Response
{
public:
    virtual ~GetNearbyStopsResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonObject) final;
    
    SwaggerLocationList Content;
};

}
