/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
#pragma once

#include "SwaggerBaseModel.h"
#include "SwaggerNote.h"

namespace Swagger 
{

/*
 * SwaggerNotes
 *
 * 
 */
class VASTTRAFIK_API SwaggerNotes : public Model
{
public:
    virtual ~SwaggerNotes() {}
	bool FromJson(const TSharedPtr<FJsonObject>& JsonObject) final;
	void WriteJson(JsonWriter& Writer) const final;

	TOptional<TArray<SwaggerNote>> Note;
};

}
