/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
#pragma once

#include "CoreMinimal.h"
#include "SwaggerBaseModel.h"

namespace Swagger 
{

class VASTTRAFIK_API SwaggerSysteminfoApi
{
public:
	SwaggerSysteminfoApi();
	~SwaggerSysteminfoApi();

	void SetURL(const FString& Url);
	void AddHeaderParam(const FString& Key, const FString& Value);
	void ClearHeaderParams();

	class GetSystemInfoRequest;
	class GetSystemInfoResponse;
	
    DECLARE_DELEGATE_OneParam(FGetSystemInfoDelegate, const GetSystemInfoResponse&);
    
    bool GetSystemInfo(const GetSystemInfoRequest& Request, const FGetSystemInfoDelegate& Delegate = FGetSystemInfoDelegate()) const;
    
private:
    void OnGetSystemInfoResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FGetSystemInfoDelegate Delegate) const;
    
	bool IsValid() const;
	void HandleResponse(FHttpResponsePtr HttpResponse, bool bSucceeded, Response& InOutResponse) const;

	FString Url;
	TMap<FString,FString> AdditionalHeaderParams;
};
	
}
