/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
#pragma once

#include "SwaggerBaseModel.h"

namespace Swagger 
{

/*
 * SwaggerColor
 *
 * 
 */
class VASTTRAFIK_API SwaggerColor : public Model
{
public:
    virtual ~SwaggerColor() {}
	bool FromJson(const TSharedPtr<FJsonObject>& JsonObject) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* Backgroundcolor of this line */
	FString BgColor;
	/* Foregroundcolor of this line */
	FString FgColor;
	/* Stroke style of this line */
	FString Stroke;
};

}
