/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
#pragma once

#include "CoreMinimal.h"
#include "SwaggerBaseModel.h"

namespace Swagger 
{

class VASTTRAFIK_API SwaggerLocationApi
{
public:
	SwaggerLocationApi();
	~SwaggerLocationApi();

	void SetURL(const FString& Url);
	void AddHeaderParam(const FString& Key, const FString& Value);
	void ClearHeaderParams();

	class GetAllStopsRequest;
	class GetAllStopsResponse;
	class GetLocationByNameRequest;
	class GetLocationByNameResponse;
	class GetNearbyAddressRequest;
	class GetNearbyAddressResponse;
	class GetNearbyStopsRequest;
	class GetNearbyStopsResponse;
	
    DECLARE_DELEGATE_OneParam(FGetAllStopsDelegate, const GetAllStopsResponse&);
    DECLARE_DELEGATE_OneParam(FGetLocationByNameDelegate, const GetLocationByNameResponse&);
    DECLARE_DELEGATE_OneParam(FGetNearbyAddressDelegate, const GetNearbyAddressResponse&);
    DECLARE_DELEGATE_OneParam(FGetNearbyStopsDelegate, const GetNearbyStopsResponse&);
    
    bool GetAllStops(const GetAllStopsRequest& Request, const FGetAllStopsDelegate& Delegate = FGetAllStopsDelegate()) const;
    bool GetLocationByName(const GetLocationByNameRequest& Request, const FGetLocationByNameDelegate& Delegate = FGetLocationByNameDelegate()) const;
    bool GetNearbyAddress(const GetNearbyAddressRequest& Request, const FGetNearbyAddressDelegate& Delegate = FGetNearbyAddressDelegate()) const;
    bool GetNearbyStops(const GetNearbyStopsRequest& Request, const FGetNearbyStopsDelegate& Delegate = FGetNearbyStopsDelegate()) const;
    
private:
    void OnGetAllStopsResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FGetAllStopsDelegate Delegate) const;
    void OnGetLocationByNameResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FGetLocationByNameDelegate Delegate) const;
    void OnGetNearbyAddressResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FGetNearbyAddressDelegate Delegate) const;
    void OnGetNearbyStopsResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FGetNearbyStopsDelegate Delegate) const;
    
	bool IsValid() const;
	void HandleResponse(FHttpResponsePtr HttpResponse, bool bSucceeded, Response& InOutResponse) const;

	FString Url;
	TMap<FString,FString> AdditionalHeaderParams;
};
	
}
