/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
#pragma once

#include "SwaggerBaseModel.h"
#include "SwaggerColor.h"
#include "SwaggerDirection.h"
#include "SwaggerGeometryRef.h"
#include "SwaggerJourneyId.h"
#include "SwaggerJourneyName.h"
#include "SwaggerJourneyType.h"
#include "SwaggerStop.h"

namespace Swagger 
{

/*
 * SwaggerJourneyDetail
 *
 * 
 */
class VASTTRAFIK_API SwaggerJourneyDetail : public Model
{
public:
    virtual ~SwaggerJourneyDetail() {}
	bool FromJson(const TSharedPtr<FJsonObject>& JsonObject) final;
	void WriteJson(JsonWriter& Writer) const final;

	TOptional<SwaggerJourneyType> JourneyType;
	TOptional<FString> ErrorText;
	TOptional<FString> Error;
	TOptional<FDateTime> Serverdate;
	/* Current server time in format HH:MM */
	TOptional<FString> Servertime;
	TOptional<SwaggerJourneyId> JourneyId;
	TOptional<SwaggerDirection> Direction;
	TOptional<TArray<SwaggerStop>> Stop;
	TOptional<SwaggerJourneyName> JourneyName;
	TOptional<SwaggerGeometryRef> GeometryRef;
	TOptional<SwaggerColor> Color;
	FString NoNamespaceSchemaLocation;
};

}
