/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
#include "SwaggerTripList.h"

#include "VasttrafikModule.h"
#include "SwaggerHelpers.h"

#include "Templates/SharedPointer.h"

namespace Swagger 
{

void SwaggerTripList::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	if (ErrorText.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("errorText")); WriteJsonValue(Writer, ErrorText.GetValue());	
	}
	if (Error.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("error")); WriteJsonValue(Writer, Error.GetValue());	
	}
	if (Serverdate.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("serverdate")); WriteJsonValue(Writer, Serverdate.GetValue());	
	}
	if (Servertime.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("servertime")); WriteJsonValue(Writer, Servertime.GetValue());	
	}
	if (Trip.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("Trip")); WriteJsonValue(Writer, Trip.GetValue());	
	}
	Writer->WriteIdentifierPrefix(TEXT("noNamespaceSchemaLocation")); WriteJsonValue(Writer, NoNamespaceSchemaLocation);
	Writer->WriteObjectEnd();
}

bool SwaggerTripList::FromJson(const TSharedPtr<FJsonObject>& JsonObject)
{
	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("errorText"), ErrorText);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("error"), Error);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("serverdate"), Serverdate);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("servertime"), Servertime);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("Trip"), Trip);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("noNamespaceSchemaLocation"), NoNamespaceSchemaLocation);

	return ParseSuccess;
}
}
