/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
#include "SwaggerLocationApiOperations.h"

#include "VasttrafikModule.h"
#include "SwaggerHelpers.h"

#include "Dom/JsonObject.h"
#include "Templates/SharedPointer.h"
#include "HttpModule.h"
#include "PlatformHttp.h"

namespace Swagger 
{

FString SwaggerLocationApi::GetAllStopsRequest::ComputePath() const
{
	FString Path(TEXT("/location.allstops"));
	TArray<FString> QueryParams;
	if(Format.IsSet())
	{
		QueryParams.Add(FString(TEXT("format=")) + ToUrlString(Format.GetValue()));
	}
	if(JsonpCallback.IsSet())
	{
		QueryParams.Add(FString(TEXT("jsonpCallback=")) + ToUrlString(JsonpCallback.GetValue()));
	}
	Path += TCHAR('?');
	Path += FString::Join(QueryParams, TEXT("&"));

	return Path;
}

void SwaggerLocationApi::GetAllStopsRequest::SetupHttpRequest(const TSharedRef<IHttpRequest, ESPMode::ThreadSafe>& HttpRequest) const
{
	static const TArray<FString> Consumes = {  };
	//static const TArray<FString> Produces = { TEXT("application/xml"), TEXT("application/json") };

	HttpRequest->SetVerb(TEXT("GET"));

	// Default to Json Body request
	if (Consumes.Num() == 0 || Consumes.Contains(TEXT("application/json")))
	{
	}
	else if (Consumes.Contains(TEXT("multipart/form-data")))
	{
	}
	else if (Consumes.Contains(TEXT("application/x-www-form-urlencoded")))
	{
	}
	else
	{
		UE_LOG(LogSwagger, Error, TEXT("Request ContentType not supported (%s)"), *FString::Join(Consumes, TEXT(",")));
	}
}

void SwaggerLocationApi::GetAllStopsResponse::SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode)
{
	Response::SetHttpResponseCode(InHttpResponseCode);
	switch ((int)InHttpResponseCode)
	{
	case 200:
	default:
		SetResponseString(TEXT("success"));
		break;
	case 401:
		SetResponseString(TEXT("Unauthorized"));
		break;
	case 500:
		SetResponseString(TEXT("Internal server error"));
		break;
	}
}

bool SwaggerLocationApi::GetAllStopsResponse::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	return TryGetJsonValue(JsonValue, Content);
}

FString SwaggerLocationApi::GetLocationByNameRequest::ComputePath() const
{
	FString Path(TEXT("/location.name"));
	TArray<FString> QueryParams;
	if(Input.IsSet())
	{
		QueryParams.Add(FString(TEXT("input=")) + ToUrlString(Input.GetValue()));
	}
	if(Format.IsSet())
	{
		QueryParams.Add(FString(TEXT("format=")) + ToUrlString(Format.GetValue()));
	}
	if(JsonpCallback.IsSet())
	{
		QueryParams.Add(FString(TEXT("jsonpCallback=")) + ToUrlString(JsonpCallback.GetValue()));
	}
	Path += TCHAR('?');
	Path += FString::Join(QueryParams, TEXT("&"));

	return Path;
}

void SwaggerLocationApi::GetLocationByNameRequest::SetupHttpRequest(const TSharedRef<IHttpRequest, ESPMode::ThreadSafe>& HttpRequest) const
{
	static const TArray<FString> Consumes = {  };
	//static const TArray<FString> Produces = { TEXT("application/xml"), TEXT("application/json") };

	HttpRequest->SetVerb(TEXT("GET"));

	// Default to Json Body request
	if (Consumes.Num() == 0 || Consumes.Contains(TEXT("application/json")))
	{
	}
	else if (Consumes.Contains(TEXT("multipart/form-data")))
	{
	}
	else if (Consumes.Contains(TEXT("application/x-www-form-urlencoded")))
	{
	}
	else
	{
		UE_LOG(LogSwagger, Error, TEXT("Request ContentType not supported (%s)"), *FString::Join(Consumes, TEXT(",")));
	}
}

void SwaggerLocationApi::GetLocationByNameResponse::SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode)
{
	Response::SetHttpResponseCode(InHttpResponseCode);
	switch ((int)InHttpResponseCode)
	{
	case 200:
	default:
		SetResponseString(TEXT("success"));
		break;
	case 401:
		SetResponseString(TEXT("Unauthorized"));
		break;
	case 500:
		SetResponseString(TEXT("Internal server error"));
		break;
	}
}

bool SwaggerLocationApi::GetLocationByNameResponse::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	return TryGetJsonValue(JsonValue, Content);
}

FString SwaggerLocationApi::GetNearbyAddressRequest::ComputePath() const
{
	FString Path(TEXT("/location.nearbyaddress"));
	TArray<FString> QueryParams;
	QueryParams.Add(FString(TEXT("originCoordLat=")) + ToUrlString(OriginCoordLat));
	QueryParams.Add(FString(TEXT("originCoordLong=")) + ToUrlString(OriginCoordLong));
	if(Format.IsSet())
	{
		QueryParams.Add(FString(TEXT("format=")) + ToUrlString(Format.GetValue()));
	}
	if(JsonpCallback.IsSet())
	{
		QueryParams.Add(FString(TEXT("jsonpCallback=")) + ToUrlString(JsonpCallback.GetValue()));
	}
	Path += TCHAR('?');
	Path += FString::Join(QueryParams, TEXT("&"));

	return Path;
}

void SwaggerLocationApi::GetNearbyAddressRequest::SetupHttpRequest(const TSharedRef<IHttpRequest, ESPMode::ThreadSafe>& HttpRequest) const
{
	static const TArray<FString> Consumes = {  };
	//static const TArray<FString> Produces = { TEXT("application/xml"), TEXT("application/json") };

	HttpRequest->SetVerb(TEXT("GET"));

	// Default to Json Body request
	if (Consumes.Num() == 0 || Consumes.Contains(TEXT("application/json")))
	{
	}
	else if (Consumes.Contains(TEXT("multipart/form-data")))
	{
	}
	else if (Consumes.Contains(TEXT("application/x-www-form-urlencoded")))
	{
	}
	else
	{
		UE_LOG(LogSwagger, Error, TEXT("Request ContentType not supported (%s)"), *FString::Join(Consumes, TEXT(",")));
	}
}

void SwaggerLocationApi::GetNearbyAddressResponse::SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode)
{
	Response::SetHttpResponseCode(InHttpResponseCode);
	switch ((int)InHttpResponseCode)
	{
	case 200:
	default:
		SetResponseString(TEXT("success"));
		break;
	case 401:
		SetResponseString(TEXT("Unauthorized"));
		break;
	case 500:
		SetResponseString(TEXT("Internal server error"));
		break;
	}
}

bool SwaggerLocationApi::GetNearbyAddressResponse::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	return TryGetJsonValue(JsonValue, Content);
}

FString SwaggerLocationApi::GetNearbyStopsRequest::ComputePath() const
{
	FString Path(TEXT("/location.nearbystops"));
	TArray<FString> QueryParams;
	QueryParams.Add(FString(TEXT("originCoordLat=")) + ToUrlString(OriginCoordLat));
	QueryParams.Add(FString(TEXT("originCoordLong=")) + ToUrlString(OriginCoordLong));
	if(MaxNo.IsSet())
	{
		QueryParams.Add(FString(TEXT("maxNo=")) + ToUrlString(MaxNo.GetValue()));
	}
	if(MaxDist.IsSet())
	{
		QueryParams.Add(FString(TEXT("maxDist=")) + ToUrlString(MaxDist.GetValue()));
	}
	if(Format.IsSet())
	{
		QueryParams.Add(FString(TEXT("format=")) + ToUrlString(Format.GetValue()));
	}
	if(JsonpCallback.IsSet())
	{
		QueryParams.Add(FString(TEXT("jsonpCallback=")) + ToUrlString(JsonpCallback.GetValue()));
	}
	Path += TCHAR('?');
	Path += FString::Join(QueryParams, TEXT("&"));

	return Path;
}

void SwaggerLocationApi::GetNearbyStopsRequest::SetupHttpRequest(const TSharedRef<IHttpRequest, ESPMode::ThreadSafe>& HttpRequest) const
{
	static const TArray<FString> Consumes = {  };
	//static const TArray<FString> Produces = { TEXT("application/xml"), TEXT("application/json") };

	HttpRequest->SetVerb(TEXT("GET"));

	// Default to Json Body request
	if (Consumes.Num() == 0 || Consumes.Contains(TEXT("application/json")))
	{
	}
	else if (Consumes.Contains(TEXT("multipart/form-data")))
	{
	}
	else if (Consumes.Contains(TEXT("application/x-www-form-urlencoded")))
	{
	}
	else
	{
		UE_LOG(LogSwagger, Error, TEXT("Request ContentType not supported (%s)"), *FString::Join(Consumes, TEXT(",")));
	}
}

void SwaggerLocationApi::GetNearbyStopsResponse::SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode)
{
	Response::SetHttpResponseCode(InHttpResponseCode);
	switch ((int)InHttpResponseCode)
	{
	case 200:
	default:
		SetResponseString(TEXT("success"));
		break;
	case 401:
		SetResponseString(TEXT("Unauthorized"));
		break;
	case 500:
		SetResponseString(TEXT("Internal server error"));
		break;
	}
}

bool SwaggerLocationApi::GetNearbyStopsResponse::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	return TryGetJsonValue(JsonValue, Content);
}

}
