/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
#include "SwaggerTrip.h"

#include "VasttrafikModule.h"
#include "SwaggerHelpers.h"

#include "Templates/SharedPointer.h"

namespace Swagger 
{

inline FString ToString(const SwaggerTrip::TypeEnum& Value)
{
	switch (Value)
	{
	case SwaggerTrip::TypeEnum::Walk:
		return TEXT("WALK");
	case SwaggerTrip::TypeEnum::Bike:
		return TEXT("BIKE");
	case SwaggerTrip::TypeEnum::Car:
		return TEXT("CAR");
	}

	UE_LOG(LogSwagger, Error, TEXT("Invalid SwaggerTrip::TypeEnum Value (%d)"), (int)Value);	
	return TEXT("");
}

inline FStringFormatArg ToStringFormatArg(const SwaggerTrip::TypeEnum& Value)
{
	return FStringFormatArg(ToString(Value));
}

inline void WriteJsonValue(JsonWriter& Writer, const SwaggerTrip::TypeEnum& Value)
{
	WriteJsonValue(Writer, ToString(Value));
}

inline bool TryGetJsonValue(const TSharedPtr<FJsonValue>& JsonValue, SwaggerTrip::TypeEnum& Value)
{
	FString TmpValue;
	if (JsonValue->TryGetString(TmpValue))
	{
		static TMap<FString, SwaggerTrip::TypeEnum> StringToEnum = {  };

		const auto Found = StringToEnum.Find(TmpValue);
		if(Found)
		{
			Value = *Found;
			return true;
		}
	}
	return false;
}

void SwaggerTrip::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	if (Leg.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("Leg")); WriteJsonValue(Writer, Leg.GetValue());	
	}
	if (TravelWarranty.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("travelWarranty")); WriteJsonValue(Writer, TravelWarranty.GetValue());	
	}
	if (Valid.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("valid")); WriteJsonValue(Writer, Valid.GetValue());	
	}
	Writer->WriteIdentifierPrefix(TEXT("alternative")); WriteJsonValue(Writer, Alternative);
	if (Type.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("type")); WriteJsonValue(Writer, Type.GetValue());	
	}
	Writer->WriteObjectEnd();
}

bool SwaggerTrip::FromJson(const TSharedPtr<FJsonObject>& JsonObject)
{
	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("Leg"), Leg);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("travelWarranty"), TravelWarranty);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("valid"), Valid);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("alternative"), Alternative);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("type"), Type);

	return ParseSuccess;
}
}
