/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
#include "SwaggerArrival.h"

#include "VasttrafikModule.h"
#include "SwaggerHelpers.h"

#include "Templates/SharedPointer.h"

namespace Swagger 
{

inline FString ToString(const SwaggerArrival::AccessibilityEnum& Value)
{
	switch (Value)
	{
	case SwaggerArrival::AccessibilityEnum::WheelChair:
		return TEXT("wheelChair");
	case SwaggerArrival::AccessibilityEnum::LowFloor:
		return TEXT("lowFloor");
	}

	UE_LOG(LogSwagger, Error, TEXT("Invalid SwaggerArrival::AccessibilityEnum Value (%d)"), (int)Value);	
	return TEXT("");
}

inline FStringFormatArg ToStringFormatArg(const SwaggerArrival::AccessibilityEnum& Value)
{
	return FStringFormatArg(ToString(Value));
}

inline void WriteJsonValue(JsonWriter& Writer, const SwaggerArrival::AccessibilityEnum& Value)
{
	WriteJsonValue(Writer, ToString(Value));
}

inline bool TryGetJsonValue(const TSharedPtr<FJsonValue>& JsonValue, SwaggerArrival::AccessibilityEnum& Value)
{
	FString TmpValue;
	if (JsonValue->TryGetString(TmpValue))
	{
		static TMap<FString, SwaggerArrival::AccessibilityEnum> StringToEnum = {  };

		const auto Found = StringToEnum.Find(TmpValue);
		if(Found)
		{
			Value = *Found;
			return true;
		}
	}
	return false;
}

void SwaggerArrival::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("fgColor")); WriteJsonValue(Writer, FgColor);
	Writer->WriteIdentifierPrefix(TEXT("stop")); WriteJsonValue(Writer, Stop);
	if (Booking.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("booking")); WriteJsonValue(Writer, Booking.GetValue());	
	}
	Writer->WriteIdentifierPrefix(TEXT("JourneyDetailRef")); WriteJsonValue(Writer, JourneyDetailRef);
	Writer->WriteIdentifierPrefix(TEXT("origin")); WriteJsonValue(Writer, Origin);
	Writer->WriteIdentifierPrefix(TEXT("track")); WriteJsonValue(Writer, Track);
	if (RtTrack.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("rtTrack")); WriteJsonValue(Writer, RtTrack.GetValue());	
	}
	Writer->WriteIdentifierPrefix(TEXT("sname")); WriteJsonValue(Writer, Sname);
	Writer->WriteIdentifierPrefix(TEXT("type")); WriteJsonValue(Writer, Type);
	Writer->WriteIdentifierPrefix(TEXT("date")); WriteJsonValue(Writer, Date);
	Writer->WriteIdentifierPrefix(TEXT("bgColor")); WriteJsonValue(Writer, BgColor);
	Writer->WriteIdentifierPrefix(TEXT("stroke")); WriteJsonValue(Writer, Stroke);
	Writer->WriteIdentifierPrefix(TEXT("rtDate")); WriteJsonValue(Writer, RtDate);
	Writer->WriteIdentifierPrefix(TEXT("time")); WriteJsonValue(Writer, Time);
	Writer->WriteIdentifierPrefix(TEXT("name")); WriteJsonValue(Writer, Name);
	Writer->WriteIdentifierPrefix(TEXT("rtTime")); WriteJsonValue(Writer, RtTime);
	if (Night.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("night")); WriteJsonValue(Writer, Night.GetValue());	
	}
	Writer->WriteIdentifierPrefix(TEXT("stopid")); WriteJsonValue(Writer, Stopid);
	Writer->WriteIdentifierPrefix(TEXT("journeyid")); WriteJsonValue(Writer, Journeyid);
	Writer->WriteIdentifierPrefix(TEXT("accessibility")); WriteJsonValue(Writer, Accessibility);
	Writer->WriteObjectEnd();
}

bool SwaggerArrival::FromJson(const TSharedPtr<FJsonObject>& JsonObject)
{
	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("fgColor"), FgColor);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("stop"), Stop);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("booking"), Booking);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("JourneyDetailRef"), JourneyDetailRef);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("origin"), Origin);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("track"), Track);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("rtTrack"), RtTrack);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("sname"), Sname);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("type"), Type);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("date"), Date);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("bgColor"), BgColor);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("stroke"), Stroke);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("rtDate"), RtDate);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("time"), Time);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("name"), Name);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("rtTime"), RtTime);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("night"), Night);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("stopid"), Stopid);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("journeyid"), Journeyid);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("accessibility"), Accessibility);

	return ParseSuccess;
}
}
