/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
#include "SwaggerNotes.h"

#include "VasttrafikModule.h"
#include "SwaggerHelpers.h"

#include "Templates/SharedPointer.h"

namespace Swagger 
{

void SwaggerNotes::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	if (Note.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("Note")); WriteJsonValue(Writer, Note.GetValue());	
	}
	Writer->WriteObjectEnd();
}

bool SwaggerNotes::FromJson(const TSharedPtr<FJsonObject>& JsonObject)
{
	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("Note"), Note);

	return ParseSuccess;
}
}
