/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
#include "SwaggerTimeTablePeriod.h"

#include "VasttrafikModule.h"
#include "SwaggerHelpers.h"

#include "Templates/SharedPointer.h"

namespace Swagger 
{

void SwaggerTimeTablePeriod::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("DateBegin")); WriteJsonValue(Writer, DateBegin);
	Writer->WriteIdentifierPrefix(TEXT("DateEnd")); WriteJsonValue(Writer, DateEnd);
	Writer->WriteObjectEnd();
}

bool SwaggerTimeTablePeriod::FromJson(const TSharedPtr<FJsonObject>& JsonObject)
{
	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("DateBegin"), DateBegin);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("DateEnd"), DateEnd);

	return ParseSuccess;
}
}
