/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
#include "SwaggerTripApiOperations.h"

#include "VasttrafikModule.h"
#include "SwaggerHelpers.h"

#include "Dom/JsonObject.h"
#include "Templates/SharedPointer.h"
#include "HttpModule.h"
#include "PlatformHttp.h"

namespace Swagger 
{

FString SwaggerTripApi::GetTripRequest::ComputePath() const
{
	FString Path(TEXT("/trip"));
	TArray<FString> QueryParams;
	if(OriginId.IsSet())
	{
		QueryParams.Add(FString(TEXT("originId=")) + ToUrlString(OriginId.GetValue()));
	}
	if(OriginCoordLat.IsSet())
	{
		QueryParams.Add(FString(TEXT("originCoordLat=")) + ToUrlString(OriginCoordLat.GetValue()));
	}
	if(OriginCoordLong.IsSet())
	{
		QueryParams.Add(FString(TEXT("originCoordLong=")) + ToUrlString(OriginCoordLong.GetValue()));
	}
	if(OriginCoordName.IsSet())
	{
		QueryParams.Add(FString(TEXT("originCoordName=")) + ToUrlString(OriginCoordName.GetValue()));
	}
	if(DestId.IsSet())
	{
		QueryParams.Add(FString(TEXT("destId=")) + ToUrlString(DestId.GetValue()));
	}
	if(DestCoordLat.IsSet())
	{
		QueryParams.Add(FString(TEXT("destCoordLat=")) + ToUrlString(DestCoordLat.GetValue()));
	}
	if(DestCoordLong.IsSet())
	{
		QueryParams.Add(FString(TEXT("destCoordLong=")) + ToUrlString(DestCoordLong.GetValue()));
	}
	if(DestCoordName.IsSet())
	{
		QueryParams.Add(FString(TEXT("destCoordName=")) + ToUrlString(DestCoordName.GetValue()));
	}
	if(ViaId.IsSet())
	{
		QueryParams.Add(FString(TEXT("viaId=")) + ToUrlString(ViaId.GetValue()));
	}
	if(Date.IsSet())
	{
		QueryParams.Add(FString(TEXT("date=")) + ToUrlString(Date.GetValue()));
	}
	if(Time.IsSet())
	{
		QueryParams.Add(FString(TEXT("time=")) + ToUrlString(Time.GetValue()));
	}
	if(SearchForArrival.IsSet())
	{
		QueryParams.Add(FString(TEXT("searchForArrival=")) + ToUrlString(SearchForArrival.GetValue()));
	}
	if(UseVas.IsSet())
	{
		QueryParams.Add(FString(TEXT("useVas=")) + ToUrlString(UseVas.GetValue()));
	}
	if(UseLDTrain.IsSet())
	{
		QueryParams.Add(FString(TEXT("useLDTrain=")) + ToUrlString(UseLDTrain.GetValue()));
	}
	if(UseRegTrain.IsSet())
	{
		QueryParams.Add(FString(TEXT("useRegTrain=")) + ToUrlString(UseRegTrain.GetValue()));
	}
	if(UseBus.IsSet())
	{
		QueryParams.Add(FString(TEXT("useBus=")) + ToUrlString(UseBus.GetValue()));
	}
	if(UseMedical.IsSet())
	{
		QueryParams.Add(FString(TEXT("useMedical=")) + ToUrlString(UseMedical.GetValue()));
	}
	if(OriginMedicalCon.IsSet())
	{
		QueryParams.Add(FString(TEXT("originMedicalCon=")) + ToUrlString(OriginMedicalCon.GetValue()));
	}
	if(DestMedicalCon.IsSet())
	{
		QueryParams.Add(FString(TEXT("destMedicalCon=")) + ToUrlString(DestMedicalCon.GetValue()));
	}
	if(WheelChairSpace.IsSet())
	{
		QueryParams.Add(FString(TEXT("wheelChairSpace=")) + ToUrlString(WheelChairSpace.GetValue()));
	}
	if(StrollerSpace.IsSet())
	{
		QueryParams.Add(FString(TEXT("strollerSpace=")) + ToUrlString(StrollerSpace.GetValue()));
	}
	if(LowFloor.IsSet())
	{
		QueryParams.Add(FString(TEXT("lowFloor=")) + ToUrlString(LowFloor.GetValue()));
	}
	if(RampOrLift.IsSet())
	{
		QueryParams.Add(FString(TEXT("rampOrLift=")) + ToUrlString(RampOrLift.GetValue()));
	}
	if(UseBoat.IsSet())
	{
		QueryParams.Add(FString(TEXT("useBoat=")) + ToUrlString(UseBoat.GetValue()));
	}
	if(UseTram.IsSet())
	{
		QueryParams.Add(FString(TEXT("useTram=")) + ToUrlString(UseTram.GetValue()));
	}
	if(UsePT.IsSet())
	{
		QueryParams.Add(FString(TEXT("usePT=")) + ToUrlString(UsePT.GetValue()));
	}
	if(ExcludeDR.IsSet())
	{
		QueryParams.Add(FString(TEXT("excludeDR=")) + ToUrlString(ExcludeDR.GetValue()));
	}
	if(MaxWalkDist.IsSet())
	{
		QueryParams.Add(FString(TEXT("maxWalkDist=")) + ToUrlString(MaxWalkDist.GetValue()));
	}
	if(WalkSpeed.IsSet())
	{
		QueryParams.Add(FString(TEXT("walkSpeed=")) + ToUrlString(WalkSpeed.GetValue()));
	}
	if(OriginWalk.IsSet())
	{
		QueryParams.Add(FString(TEXT("originWalk=")) + ToUrlString(OriginWalk.GetValue()));
	}
	if(DestWalk.IsSet())
	{
		QueryParams.Add(FString(TEXT("destWalk=")) + ToUrlString(DestWalk.GetValue()));
	}
	if(OnlyWalk.IsSet())
	{
		QueryParams.Add(FString(TEXT("onlyWalk=")) + ToUrlString(OnlyWalk.GetValue()));
	}
	if(OriginBike.IsSet())
	{
		QueryParams.Add(FString(TEXT("originBike=")) + ToUrlString(OriginBike.GetValue()));
	}
	if(MaxBikeDist.IsSet())
	{
		QueryParams.Add(FString(TEXT("maxBikeDist=")) + ToUrlString(MaxBikeDist.GetValue()));
	}
	if(BikeCriterion.IsSet())
	{
		QueryParams.Add(FString(TEXT("bikeCriterion=")) + ToUrlString(BikeCriterion.GetValue()));
	}
	if(BikeProfile.IsSet())
	{
		QueryParams.Add(FString(TEXT("bikeProfile=")) + ToUrlString(BikeProfile.GetValue()));
	}
	if(OnlyBike.IsSet())
	{
		QueryParams.Add(FString(TEXT("onlyBike=")) + ToUrlString(OnlyBike.GetValue()));
	}
	if(OriginCar.IsSet())
	{
		QueryParams.Add(FString(TEXT("originCar=")) + ToUrlString(OriginCar.GetValue()));
	}
	if(OriginCarWithParking.IsSet())
	{
		QueryParams.Add(FString(TEXT("originCarWithParking=")) + ToUrlString(OriginCarWithParking.GetValue()));
	}
	if(MaxCarDist.IsSet())
	{
		QueryParams.Add(FString(TEXT("maxCarDist=")) + ToUrlString(MaxCarDist.GetValue()));
	}
	if(OnlyCar.IsSet())
	{
		QueryParams.Add(FString(TEXT("onlyCar=")) + ToUrlString(OnlyCar.GetValue()));
	}
	if(MaxChanges.IsSet())
	{
		QueryParams.Add(FString(TEXT("maxChanges=")) + ToUrlString(MaxChanges.GetValue()));
	}
	if(AdditionalChangeTime.IsSet())
	{
		QueryParams.Add(FString(TEXT("additionalChangeTime=")) + ToUrlString(AdditionalChangeTime.GetValue()));
	}
	if(DisregardDefaultChangeMargin.IsSet())
	{
		QueryParams.Add(FString(TEXT("disregardDefaultChangeMargin=")) + ToUrlString(DisregardDefaultChangeMargin.GetValue()));
	}
	if(NeedJourneyDetail.IsSet())
	{
		QueryParams.Add(FString(TEXT("needJourneyDetail=")) + ToUrlString(NeedJourneyDetail.GetValue()));
	}
	if(NeedGeo.IsSet())
	{
		QueryParams.Add(FString(TEXT("needGeo=")) + ToUrlString(NeedGeo.GetValue()));
	}
	if(NeedItinerary.IsSet())
	{
		QueryParams.Add(FString(TEXT("needItinerary=")) + ToUrlString(NeedItinerary.GetValue()));
	}
	if(NumTrips.IsSet())
	{
		QueryParams.Add(FString(TEXT("numTrips=")) + ToUrlString(NumTrips.GetValue()));
	}
	if(Format.IsSet())
	{
		QueryParams.Add(FString(TEXT("format=")) + ToUrlString(Format.GetValue()));
	}
	if(JsonpCallback.IsSet())
	{
		QueryParams.Add(FString(TEXT("jsonpCallback=")) + ToUrlString(JsonpCallback.GetValue()));
	}
	Path += TCHAR('?');
	Path += FString::Join(QueryParams, TEXT("&"));

	return Path;
}

void SwaggerTripApi::GetTripRequest::SetupHttpRequest(const TSharedRef<IHttpRequest, ESPMode::ThreadSafe>& HttpRequest) const
{
	static const TArray<FString> Consumes = {  };
	//static const TArray<FString> Produces = { TEXT("application/xml"), TEXT("application/json") };

	HttpRequest->SetVerb(TEXT("GET"));

	// Default to Json Body request
	if (Consumes.Num() == 0 || Consumes.Contains(TEXT("application/json")))
	{
	}
	else if (Consumes.Contains(TEXT("multipart/form-data")))
	{
	}
	else if (Consumes.Contains(TEXT("application/x-www-form-urlencoded")))
	{
	}
	else
	{
		UE_LOG(LogSwagger, Error, TEXT("Request ContentType not supported (%s)"), *FString::Join(Consumes, TEXT(",")));
	}
}

void SwaggerTripApi::GetTripResponse::SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode)
{
	Response::SetHttpResponseCode(InHttpResponseCode);
	switch ((int)InHttpResponseCode)
	{
	case 200:
	default:
		SetResponseString(TEXT("success"));
		break;
	case 401:
		SetResponseString(TEXT("Unauthorized"));
		break;
	case 500:
		SetResponseString(TEXT("Internal server error"));
		break;
	}
}

bool SwaggerTripApi::GetTripResponse::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	return TryGetJsonValue(JsonValue, Content);
}

}
