/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
#include "SwaggerArrivalBoardApiOperations.h"

#include "VasttrafikModule.h"
#include "SwaggerHelpers.h"

#include "Dom/JsonObject.h"
#include "Templates/SharedPointer.h"
#include "HttpModule.h"
#include "PlatformHttp.h"

namespace Swagger 
{

FString SwaggerArrivalBoardApi::GetArrivalBoardRequest::ComputePath() const
{
	FString Path(TEXT("/arrivalBoard"));
	TArray<FString> QueryParams;
	QueryParams.Add(FString(TEXT("id=")) + ToUrlString(Id));
	QueryParams.Add(FString(TEXT("date=")) + ToUrlString(Date));
	QueryParams.Add(FString(TEXT("time=")) + ToUrlString(Time));
	if(UseVas.IsSet())
	{
		QueryParams.Add(FString(TEXT("useVas=")) + ToUrlString(UseVas.GetValue()));
	}
	if(UseLDTrain.IsSet())
	{
		QueryParams.Add(FString(TEXT("useLDTrain=")) + ToUrlString(UseLDTrain.GetValue()));
	}
	if(UseRegTrain.IsSet())
	{
		QueryParams.Add(FString(TEXT("useRegTrain=")) + ToUrlString(UseRegTrain.GetValue()));
	}
	if(UseBus.IsSet())
	{
		QueryParams.Add(FString(TEXT("useBus=")) + ToUrlString(UseBus.GetValue()));
	}
	if(UseBoat.IsSet())
	{
		QueryParams.Add(FString(TEXT("useBoat=")) + ToUrlString(UseBoat.GetValue()));
	}
	if(UseTram.IsSet())
	{
		QueryParams.Add(FString(TEXT("useTram=")) + ToUrlString(UseTram.GetValue()));
	}
	if(ExcludeDR.IsSet())
	{
		QueryParams.Add(FString(TEXT("excludeDR=")) + ToUrlString(ExcludeDR.GetValue()));
	}
	if(TimeSpan.IsSet())
	{
		QueryParams.Add(FString(TEXT("timeSpan=")) + ToUrlString(TimeSpan.GetValue()));
	}
	if(MaxDeparturesPerLine.IsSet())
	{
		QueryParams.Add(FString(TEXT("maxDeparturesPerLine=")) + ToUrlString(MaxDeparturesPerLine.GetValue()));
	}
	if(NeedJourneyDetail.IsSet())
	{
		QueryParams.Add(FString(TEXT("needJourneyDetail=")) + ToUrlString(NeedJourneyDetail.GetValue()));
	}
	QueryParams.Add(FString(TEXT("direction=")) + ToUrlString(Direction));
	if(Format.IsSet())
	{
		QueryParams.Add(FString(TEXT("format=")) + ToUrlString(Format.GetValue()));
	}
	if(JsonpCallback.IsSet())
	{
		QueryParams.Add(FString(TEXT("jsonpCallback=")) + ToUrlString(JsonpCallback.GetValue()));
	}
	Path += TCHAR('?');
	Path += FString::Join(QueryParams, TEXT("&"));

	return Path;
}

void SwaggerArrivalBoardApi::GetArrivalBoardRequest::SetupHttpRequest(const TSharedRef<IHttpRequest, ESPMode::ThreadSafe>& HttpRequest) const
{
	static const TArray<FString> Consumes = {  };
	//static const TArray<FString> Produces = { TEXT("application/xml"), TEXT("application/json") };

	HttpRequest->SetVerb(TEXT("GET"));

	// Default to Json Body request
	if (Consumes.Num() == 0 || Consumes.Contains(TEXT("application/json")))
	{
	}
	else if (Consumes.Contains(TEXT("multipart/form-data")))
	{
	}
	else if (Consumes.Contains(TEXT("application/x-www-form-urlencoded")))
	{
	}
	else
	{
		UE_LOG(LogSwagger, Error, TEXT("Request ContentType not supported (%s)"), *FString::Join(Consumes, TEXT(",")));
	}
}

void SwaggerArrivalBoardApi::GetArrivalBoardResponse::SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode)
{
	Response::SetHttpResponseCode(InHttpResponseCode);
	switch ((int)InHttpResponseCode)
	{
	case 200:
	default:
		SetResponseString(TEXT("success"));
		break;
	case 401:
		SetResponseString(TEXT("Unauthorized"));
		break;
	case 500:
		SetResponseString(TEXT("Internal server error"));
		break;
	}
}

bool SwaggerArrivalBoardApi::GetArrivalBoardResponse::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	return TryGetJsonValue(JsonValue, Content);
}

}
