/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
#include "SwaggerLivemapApiOperations.h"

#include "VasttrafikModule.h"
#include "SwaggerHelpers.h"

#include "Dom/JsonObject.h"
#include "Templates/SharedPointer.h"
#include "HttpModule.h"
#include "PlatformHttp.h"

namespace Swagger 
{

inline FString ToString(const SwaggerLivemapApi::LivemapRequest::OnlyRealtimeEnum& Value)
{
	switch (Value)
	{
	case SwaggerLivemapApi::LivemapRequest::OnlyRealtimeEnum::Yes:
		return TEXT("yes");
	case SwaggerLivemapApi::LivemapRequest::OnlyRealtimeEnum::No:
		return TEXT("no");
	}

	UE_LOG(LogSwagger, Error, TEXT("Invalid SwaggerLivemapApi::LivemapRequest::OnlyRealtimeEnum Value (%d)"), (int)Value);	
	return TEXT("");
}

inline FStringFormatArg ToStringFormatArg(const SwaggerLivemapApi::LivemapRequest::OnlyRealtimeEnum& Value)
{
	return FStringFormatArg(ToString(Value));
}

inline void WriteJsonValue(JsonWriter& Writer, const SwaggerLivemapApi::LivemapRequest::OnlyRealtimeEnum& Value)
{
	WriteJsonValue(Writer, ToString(Value));
}

inline bool TryGetJsonValue(const TSharedPtr<FJsonValue>& JsonValue, SwaggerLivemapApi::LivemapRequest::OnlyRealtimeEnum& Value)
{
	FString TmpValue;
	if (JsonValue->TryGetString(TmpValue))
	{
		static TMap<FString, SwaggerLivemapApi::LivemapRequest::OnlyRealtimeEnum> StringToEnum = { 
			{ TEXT("yes"), SwaggerLivemapApi::LivemapRequest::OnlyRealtimeEnum::Yes },
			{ TEXT("no"), SwaggerLivemapApi::LivemapRequest::OnlyRealtimeEnum::No }, };

		const auto Found = StringToEnum.Find(TmpValue);
		if(Found)
		{
			Value = *Found;
			return true;
		}
	}
	return false;
}

FString SwaggerLivemapApi::LivemapRequest::ComputePath() const
{
	FString Path(TEXT("/livemap"));
	TArray<FString> QueryParams;
	QueryParams.Add(FString(TEXT("minx=")) + ToUrlString(Minx));
	QueryParams.Add(FString(TEXT("maxx=")) + ToUrlString(Maxx));
	QueryParams.Add(FString(TEXT("miny=")) + ToUrlString(Miny));
	QueryParams.Add(FString(TEXT("maxy=")) + ToUrlString(Maxy));
	QueryParams.Add(FString(TEXT("onlyRealtime=")) + ToUrlString(OnlyRealtime));
	Path += TCHAR('?');
	Path += FString::Join(QueryParams, TEXT("&"));

	return Path;
}

void SwaggerLivemapApi::LivemapRequest::SetupHttpRequest(const TSharedRef<IHttpRequest, ESPMode::ThreadSafe>& HttpRequest) const
{
	static const TArray<FString> Consumes = {  };
	//static const TArray<FString> Produces = { TEXT("application/json") };

	HttpRequest->SetVerb(TEXT("GET"));

	// Default to Json Body request
	if (Consumes.Num() == 0 || Consumes.Contains(TEXT("application/json")))
	{
	}
	else if (Consumes.Contains(TEXT("multipart/form-data")))
	{
	}
	else if (Consumes.Contains(TEXT("application/x-www-form-urlencoded")))
	{
	}
	else
	{
		UE_LOG(LogSwagger, Error, TEXT("Request ContentType not supported (%s)"), *FString::Join(Consumes, TEXT(",")));
	}
}

void SwaggerLivemapApi::LivemapResponse::SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode)
{
	Response::SetHttpResponseCode(InHttpResponseCode);
	switch ((int)InHttpResponseCode)
	{
	case 200:
	default:
		SetResponseString(TEXT("success"));
		break;
	case 401:
		SetResponseString(TEXT("Unauthorized"));
		break;
	case 403:
		SetResponseString(TEXT("Missing or invalid request parameters"));
		break;
	case 415:
		SetResponseString(TEXT("Unsupported media type"));
		break;
	case 500:
		SetResponseString(TEXT("Internal server error"));
		break;
	}
}

bool SwaggerLivemapApi::LivemapResponse::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	return TryGetJsonValue(JsonValue, Content);
}

}
