/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
#include "SwaggerPoint.h"

#include "VasttrafikModule.h"
#include "SwaggerHelpers.h"

#include "Templates/SharedPointer.h"

namespace Swagger 
{

void SwaggerPoint::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("lon")); WriteJsonValue(Writer, Lon);
	Writer->WriteIdentifierPrefix(TEXT("lat")); WriteJsonValue(Writer, Lat);
	Writer->WriteObjectEnd();
}

bool SwaggerPoint::FromJson(const TSharedPtr<FJsonObject>& JsonObject)
{
	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("lon"), Lon);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("lat"), Lat);

	return ParseSuccess;
}
}
