/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
#include "SwaggerJourneyName.h"

#include "VasttrafikModule.h"
#include "SwaggerHelpers.h"

#include "Templates/SharedPointer.h"

namespace Swagger 
{

void SwaggerJourneyName::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("routeIdxTo")); WriteJsonValue(Writer, RouteIdxTo);
	Writer->WriteIdentifierPrefix(TEXT("routeIdxFrom")); WriteJsonValue(Writer, RouteIdxFrom);
	Writer->WriteIdentifierPrefix(TEXT("name")); WriteJsonValue(Writer, Name);
	Writer->WriteObjectEnd();
}

bool SwaggerJourneyName::FromJson(const TSharedPtr<FJsonObject>& JsonObject)
{
	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("routeIdxTo"), RouteIdxTo);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("routeIdxFrom"), RouteIdxFrom);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("name"), Name);

	return ParseSuccess;
}
}
