/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
#include "SwaggerTimetableInfo.h"

#include "VasttrafikModule.h"
#include "SwaggerHelpers.h"

#include "Templates/SharedPointer.h"

namespace Swagger 
{

void SwaggerTimetableInfo::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("TimeTableData")); WriteJsonValue(Writer, TimeTableData);
	Writer->WriteIdentifierPrefix(TEXT("TimeTablePeriod")); WriteJsonValue(Writer, TimeTablePeriod);
	Writer->WriteObjectEnd();
}

bool SwaggerTimetableInfo::FromJson(const TSharedPtr<FJsonObject>& JsonObject)
{
	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("TimeTableData"), TimeTableData);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("TimeTablePeriod"), TimeTablePeriod);

	return ParseSuccess;
}
}
