/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
#include "SwaggerStopLocation.h"

#include "VasttrafikModule.h"
#include "SwaggerHelpers.h"

#include "Templates/SharedPointer.h"

namespace Swagger 
{

void SwaggerStopLocation::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("id")); WriteJsonValue(Writer, Id);
	Writer->WriteIdentifierPrefix(TEXT("lon")); WriteJsonValue(Writer, Lon);
	Writer->WriteIdentifierPrefix(TEXT("idx")); WriteJsonValue(Writer, Idx);
	if (Weight.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("weight")); WriteJsonValue(Writer, Weight.GetValue());	
	}
	Writer->WriteIdentifierPrefix(TEXT("name")); WriteJsonValue(Writer, Name);
	if (Track.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("track")); WriteJsonValue(Writer, Track.GetValue());	
	}
	Writer->WriteIdentifierPrefix(TEXT("lat")); WriteJsonValue(Writer, Lat);
	Writer->WriteObjectEnd();
}

bool SwaggerStopLocation::FromJson(const TSharedPtr<FJsonObject>& JsonObject)
{
	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("id"), Id);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("lon"), Lon);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("idx"), Idx);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("weight"), Weight);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("name"), Name);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("track"), Track);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("lat"), Lat);

	return ParseSuccess;
}
}
