/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
#include "SwaggerColor.h"

#include "VasttrafikModule.h"
#include "SwaggerHelpers.h"

#include "Templates/SharedPointer.h"

namespace Swagger 
{

void SwaggerColor::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("bgColor")); WriteJsonValue(Writer, BgColor);
	Writer->WriteIdentifierPrefix(TEXT("fgColor")); WriteJsonValue(Writer, FgColor);
	Writer->WriteIdentifierPrefix(TEXT("stroke")); WriteJsonValue(Writer, Stroke);
	Writer->WriteObjectEnd();
}

bool SwaggerColor::FromJson(const TSharedPtr<FJsonObject>& JsonObject)
{
	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("bgColor"), BgColor);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("fgColor"), FgColor);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("stroke"), Stroke);

	return ParseSuccess;
}
}
