/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
#include "SwaggerLiveMap.h"

#include "VasttrafikModule.h"
#include "SwaggerHelpers.h"

#include "Templates/SharedPointer.h"

namespace Swagger
{

  void SwaggerLiveMap::WriteJson(JsonWriter& Writer) const
  {
    Writer->WriteObjectStart();
    Writer->WriteIdentifierPrefix(TEXT("time")); WriteJsonValue(Writer, Time);
    Writer->WriteIdentifierPrefix(TEXT("maxx")); WriteJsonValue(Writer, Maxx);
    Writer->WriteIdentifierPrefix(TEXT("maxy")); WriteJsonValue(Writer, Maxy);
    Writer->WriteIdentifierPrefix(TEXT("vehicles")); WriteJsonValue(Writer, Vehicles);
    Writer->WriteIdentifierPrefix(TEXT("minx")); WriteJsonValue(Writer, Minx);
    Writer->WriteIdentifierPrefix(TEXT("miny")); WriteJsonValue(Writer, Miny);
    Writer->WriteObjectEnd();
  }

  bool SwaggerLiveMap::FromJson(const TSharedPtr<FJsonObject>& JsonObject)
  {
    auto LivemapValueField = JsonObject->TryGetField("livemap");
    if (LivemapValueField) {
      TSharedPtr<FJsonObject> LivemapObject = LivemapValueField->AsObject();
      bool ParseSuccess = true;
      FString TimeString;
      //Time = FDateTime::Now();
      auto ParseTime = [](const FString& Time, int32& Hour, int32& Minute, int32& Second) -> bool
      {
        // 2DIGIT ":" 2DIGIT ":" 2DIGIT
        // ; 00:00 : 00 - 23 : 59 : 59
        TArray<FString> Tokens;

        // split up on a single delimiter
        int32 NumTokens = Time.ParseIntoArray(Tokens, TEXT(":"), true);

        if (NumTokens == 3)
        {
          Hour = FCString::Atoi(*Tokens[0]);
          Minute = FCString::Atoi(*Tokens[1]);
          Second = FCString::Atoi(*Tokens[2]);

          return (Hour >= 0 && Hour < 24) && (Minute >= 0 && Minute <= 59) && (Second >= 0 && Second <= 59);
        }

        return false;
      };
      Time = FDateTime::Now();
      if (LivemapObject->TryGetStringField("time", TimeString))
      {
        int32 Hour, Minute, Second;
        ParseSuccess &= ParseTime(TimeString, Hour, Minute, Second);
        Time = FDateTime(Time.GetYear(), Time.GetMonth(), Time.GetDay(), Hour, Minute, Second);
      }
      ParseSuccess &= TryGetJsonValue(LivemapObject, TEXT("maxx"), Maxx);
      ParseSuccess &= TryGetJsonValue(LivemapObject, TEXT("maxy"), Maxy);
      ParseSuccess &= TryGetJsonValue(LivemapObject, TEXT("vehicles"), Vehicles);
      ParseSuccess &= TryGetJsonValue(LivemapObject, TEXT("minx"), Minx);
      ParseSuccess &= TryGetJsonValue(LivemapObject, TEXT("miny"), Miny);

      return ParseSuccess;
    }



    return false;
  }
}
