/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
#include "SwaggerVehicle.h"

#include "VasttrafikModule.h"
#include "SwaggerHelpers.h"

#include "Templates/SharedPointer.h"

namespace Swagger
{

  inline FString ToString(const VehicleType& Value)
  {
    switch (Value)
    {
    case VehicleType::Vas:
      return TEXT("VAS");
    case VehicleType::Ldt:
      return TEXT("LDT");
    case VehicleType::Reg:
      return TEXT("REG");
    case VehicleType::Bus:
      return TEXT("BUS");
    case VehicleType::Boat:
      return TEXT("BOAT");
    case VehicleType::Tram:
      return TEXT("TRAM");
    case VehicleType::Taxi:
      return TEXT("TAXI");
    case VehicleType::Unknown:
      return TEXT("?");
    }

    UE_LOG(LogSwagger, Error, TEXT("Invalid VehicleType Value (%d)"), (int)Value);
    return TEXT("");
  }

  inline FStringFormatArg ToStringFormatArg(const VehicleType& Value)
  {
    return FStringFormatArg(ToString(Value));
  }

  inline void WriteJsonValue(JsonWriter& Writer, const VehicleType& Value)
  {
    WriteJsonValue(Writer, ToString(Value));
  }

  inline bool TryGetJsonValue(const TSharedPtr<FJsonValue>& JsonValue, VehicleType& Value)
  {
    FString TmpValue;
    if (JsonValue->TryGetString(TmpValue))
    {
      static TMap<FString, VehicleType> StringToEnum = {
        {TEXT("VAS"), VehicleType::Vas},
        {TEXT("LDT"), VehicleType::Ldt},
        {TEXT("REG"), VehicleType::Reg},
        {TEXT("BUS"), VehicleType::Bus},
        {TEXT("BOAT"), VehicleType::Boat},
        {TEXT("TRAM"), VehicleType::Tram},
        {TEXT("TAXI"), VehicleType::Taxi},
        {TEXT("?"), VehicleType::Unknown},
      };

      const auto Found = StringToEnum.Find(TmpValue);
      if (Found)
      {
        Value = *Found;
        return true;
      }
    }
    return false;
  }

  void SwaggerVehicle::WriteJson(JsonWriter& Writer) const
  {
    Writer->WriteObjectStart();
    Writer->WriteIdentifierPrefix(TEXT("lcolor")); WriteJsonValue(Writer, Lcolor);
    Writer->WriteIdentifierPrefix(TEXT("prodclass")); WriteJsonValue(Writer, ProdClass);
    Writer->WriteIdentifierPrefix(TEXT("bcolor")); WriteJsonValue(Writer, Bcolor);
    Writer->WriteIdentifierPrefix(TEXT("direction")); WriteJsonValue(Writer, Direction);
    Writer->WriteIdentifierPrefix(TEXT("name")); WriteJsonValue(Writer, Name);
    Writer->WriteIdentifierPrefix(TEXT("gid")); WriteJsonValue(Writer, Gid);
    Writer->WriteIdentifierPrefix(TEXT("delay")); WriteJsonValue(Writer, Delay);
    Writer->WriteIdentifierPrefix(TEXT("y")); WriteJsonValue(Writer, Y);
    Writer->WriteIdentifierPrefix(TEXT("x")); WriteJsonValue(Writer, X);
    Writer->WriteObjectEnd();
  }

  bool SwaggerVehicle::FromJson(const TSharedPtr<FJsonObject>& JsonObject)
  {
    bool ParseSuccess = true;

    ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("lcolor"), Lcolor);
    ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("prodclass"), ProdClass);
    ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("bcolor"), Bcolor);
    ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("direction"), Direction);
    ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("name"), Name);
    ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("gid"), Gid);
    //Sometimes the "delay" field is not returned. Let's just attempt to set it.
    TryGetJsonValue(JsonObject, TEXT("delay"), Delay);
    ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("y"), Y);
    ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("x"), X);
    Y /= 1000000.0;
    X /= 1000000.0;

    return ParseSuccess;
  }
}
