/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
#include "SwaggerNote.h"

#include "VasttrafikModule.h"
#include "SwaggerHelpers.h"

#include "Templates/SharedPointer.h"

namespace Swagger 
{

inline FString ToString(const SwaggerNote::SeverityEnum& Value)
{
	switch (Value)
	{
	case SwaggerNote::SeverityEnum::High:
		return TEXT("high");
	case SwaggerNote::SeverityEnum::Normal:
		return TEXT("normal");
	case SwaggerNote::SeverityEnum::Low:
		return TEXT("low");
	}

	UE_LOG(LogSwagger, Error, TEXT("Invalid SwaggerNote::SeverityEnum Value (%d)"), (int)Value);	
	return TEXT("");
}

inline FStringFormatArg ToStringFormatArg(const SwaggerNote::SeverityEnum& Value)
{
	return FStringFormatArg(ToString(Value));
}

inline void WriteJsonValue(JsonWriter& Writer, const SwaggerNote::SeverityEnum& Value)
{
	WriteJsonValue(Writer, ToString(Value));
}

inline bool TryGetJsonValue(const TSharedPtr<FJsonValue>& JsonValue, SwaggerNote::SeverityEnum& Value)
{
	FString TmpValue;
	if (JsonValue->TryGetString(TmpValue))
	{
		static TMap<FString, SwaggerNote::SeverityEnum> StringToEnum = {  };

		const auto Found = StringToEnum.Find(TmpValue);
		if(Found)
		{
			Value = *Found;
			return true;
		}
	}
	return false;
}

void SwaggerNote::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("priority")); WriteJsonValue(Writer, Priority);
	Writer->WriteIdentifierPrefix(TEXT("severity")); WriteJsonValue(Writer, Severity);
	if (Key.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("key")); WriteJsonValue(Writer, Key.GetValue());	
	}
	Writer->WriteObjectEnd();
}

bool SwaggerNote::FromJson(const TSharedPtr<FJsonObject>& JsonObject)
{
	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("priority"), Priority);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("severity"), Severity);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("key"), Key);

	return ParseSuccess;
}
}
