/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
#include "SwaggerLeg.h"

#include "VasttrafikModule.h"
#include "SwaggerHelpers.h"

#include "Templates/SharedPointer.h"

namespace Swagger 
{

void SwaggerLeg::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	if (FgColor.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("fgColor")); WriteJsonValue(Writer, FgColor.GetValue());	
	}
	if (Booking.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("booking")); WriteJsonValue(Writer, Booking.GetValue());	
	}
	if (Direction.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("direction")); WriteJsonValue(Writer, Direction.GetValue());	
	}
	if (JourneyDetailRef.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("JourneyDetailRef")); WriteJsonValue(Writer, JourneyDetailRef.GetValue());	
	}
	if (Cancelled.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("cancelled")); WriteJsonValue(Writer, Cancelled.GetValue());	
	}
	if (Kcal.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("kcal")); WriteJsonValue(Writer, Kcal.GetValue());	
	}
	if (Origin.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("Origin")); WriteJsonValue(Writer, Origin.GetValue());	
	}
	if (Sname.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("sname")); WriteJsonValue(Writer, Sname.GetValue());	
	}
	Writer->WriteIdentifierPrefix(TEXT("type")); WriteJsonValue(Writer, Type);
	if (GeometryRef.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("GeometryRef")); WriteJsonValue(Writer, GeometryRef.GetValue());	
	}
	if (BgColor.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("bgColor")); WriteJsonValue(Writer, BgColor.GetValue());	
	}
	if (Notes.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("Notes")); WriteJsonValue(Writer, Notes.GetValue());	
	}
	if (Id.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("id")); WriteJsonValue(Writer, Id.GetValue());	
	}
	if (Stroke.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("stroke")); WriteJsonValue(Writer, Stroke.GetValue());	
	}
	if (Reachable.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("reachable")); WriteJsonValue(Writer, Reachable.GetValue());	
	}
	Writer->WriteIdentifierPrefix(TEXT("name")); WriteJsonValue(Writer, Name);
	if (Night.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("night")); WriteJsonValue(Writer, Night.GetValue());	
	}
	if (Destination.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("Destination")); WriteJsonValue(Writer, Destination.GetValue());	
	}
	if (PercentBikeRoad.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("percentBikeRoad")); WriteJsonValue(Writer, PercentBikeRoad.GetValue());	
	}
	if (Accessibility.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("accessibility")); WriteJsonValue(Writer, Accessibility.GetValue());	
	}
	Writer->WriteObjectEnd();
}

bool SwaggerLeg::FromJson(const TSharedPtr<FJsonObject>& JsonObject)
{
	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("fgColor"), FgColor);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("booking"), Booking);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("direction"), Direction);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("JourneyDetailRef"), JourneyDetailRef);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("cancelled"), Cancelled);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("kcal"), Kcal);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("Origin"), Origin);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("sname"), Sname);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("type"), Type);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("GeometryRef"), GeometryRef);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("bgColor"), BgColor);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("Notes"), Notes);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("id"), Id);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("stroke"), Stroke);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("reachable"), Reachable);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("name"), Name);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("night"), Night);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("Destination"), Destination);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("percentBikeRoad"), PercentBikeRoad);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("accessibility"), Accessibility);

	return ParseSuccess;
}
}
