/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
#include "SwaggerOrigin.h"

#include "VasttrafikModule.h"
#include "SwaggerHelpers.h"

#include "Templates/SharedPointer.h"

namespace Swagger 
{

void SwaggerOrigin::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	if (RouteIdx.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("routeIdx")); WriteJsonValue(Writer, RouteIdx.GetValue());	
	}
	Writer->WriteIdentifierPrefix(TEXT("$")); WriteJsonValue(Writer, Value);
	if (Cancelled.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("cancelled")); WriteJsonValue(Writer, Cancelled.GetValue());	
	}
	if (Track.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("track")); WriteJsonValue(Writer, Track.GetValue());	
	}
	if (RtTrack.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("rtTrack")); WriteJsonValue(Writer, RtTrack.GetValue());	
	}
	Writer->WriteIdentifierPrefix(TEXT("type")); WriteJsonValue(Writer, Type);
	Writer->WriteIdentifierPrefix(TEXT("date")); WriteJsonValue(Writer, Date);
	if (Notes.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("Notes")); WriteJsonValue(Writer, Notes.GetValue());	
	}
	if (Id.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("id")); WriteJsonValue(Writer, Id.GetValue());	
	}
	if (RtDate.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("rtDate")); WriteJsonValue(Writer, RtDate.GetValue());	
	}
	Writer->WriteIdentifierPrefix(TEXT("time")); WriteJsonValue(Writer, Time);
	if (Directdate.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("directdate")); WriteJsonValue(Writer, Directdate.GetValue());	
	}
	Writer->WriteIdentifierPrefix(TEXT("name")); WriteJsonValue(Writer, Name);
	if (RtTime.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("rtTime")); WriteJsonValue(Writer, RtTime.GetValue());	
	}
	if (Directtime.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("directtime")); WriteJsonValue(Writer, Directtime.GetValue());	
	}
	Writer->WriteObjectEnd();
}

bool SwaggerOrigin::FromJson(const TSharedPtr<FJsonObject>& JsonObject)
{
	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("routeIdx"), RouteIdx);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("$"), Value);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("cancelled"), Cancelled);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("track"), Track);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("rtTrack"), RtTrack);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("type"), Type);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("date"), Date);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("Notes"), Notes);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("id"), Id);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("rtDate"), RtDate);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("time"), Time);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("directdate"), Directdate);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("name"), Name);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("rtTime"), RtTime);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("directtime"), Directtime);

	return ParseSuccess;
}
}
