/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
#include "SwaggerJourneyDetail.h"

#include "VasttrafikModule.h"
#include "SwaggerHelpers.h"

#include "Templates/SharedPointer.h"

namespace Swagger 
{

void SwaggerJourneyDetail::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	if (JourneyType.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("JourneyType")); WriteJsonValue(Writer, JourneyType.GetValue());	
	}
	if (ErrorText.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("errorText")); WriteJsonValue(Writer, ErrorText.GetValue());	
	}
	if (Error.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("error")); WriteJsonValue(Writer, Error.GetValue());	
	}
	if (Serverdate.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("serverdate")); WriteJsonValue(Writer, Serverdate.GetValue());	
	}
	if (Servertime.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("servertime")); WriteJsonValue(Writer, Servertime.GetValue());	
	}
	if (JourneyId.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("JourneyId")); WriteJsonValue(Writer, JourneyId.GetValue());	
	}
	if (Direction.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("Direction")); WriteJsonValue(Writer, Direction.GetValue());	
	}
	if (Stop.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("Stop")); WriteJsonValue(Writer, Stop.GetValue());	
	}
	if (JourneyName.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("JourneyName")); WriteJsonValue(Writer, JourneyName.GetValue());	
	}
	if (GeometryRef.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("GeometryRef")); WriteJsonValue(Writer, GeometryRef.GetValue());	
	}
	if (Color.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("Color")); WriteJsonValue(Writer, Color.GetValue());	
	}
	Writer->WriteIdentifierPrefix(TEXT("noNamespaceSchemaLocation")); WriteJsonValue(Writer, NoNamespaceSchemaLocation);
	Writer->WriteObjectEnd();
}

bool SwaggerJourneyDetail::FromJson(const TSharedPtr<FJsonObject>& JsonObject)
{
	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("JourneyType"), JourneyType);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("errorText"), ErrorText);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("error"), Error);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("serverdate"), Serverdate);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("servertime"), Servertime);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("JourneyId"), JourneyId);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("Direction"), Direction);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("Stop"), Stop);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("JourneyName"), JourneyName);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("GeometryRef"), GeometryRef);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("Color"), Color);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("noNamespaceSchemaLocation"), NoNamespaceSchemaLocation);

	return ParseSuccess;
}
}
