/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
#include "SwaggerStop.h"

#include "VasttrafikModule.h"
#include "SwaggerHelpers.h"

#include "Templates/SharedPointer.h"

namespace Swagger 
{

void SwaggerStop::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("routeIdx")); WriteJsonValue(Writer, RouteIdx);
	if (ArrDate.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("arrDate")); WriteJsonValue(Writer, ArrDate.GetValue());	
	}
	if (DepTime.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("depTime")); WriteJsonValue(Writer, DepTime.GetValue());	
	}
	Writer->WriteIdentifierPrefix(TEXT("lon")); WriteJsonValue(Writer, Lon);
	if (DepDate.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("depDate")); WriteJsonValue(Writer, DepDate.GetValue());	
	}
	Writer->WriteIdentifierPrefix(TEXT("track")); WriteJsonValue(Writer, Track);
	if (RtTrack.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("rtTrack")); WriteJsonValue(Writer, RtTrack.GetValue());	
	}
	Writer->WriteIdentifierPrefix(TEXT("id")); WriteJsonValue(Writer, Id);
	if (RtDepTime.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("rtDepTime")); WriteJsonValue(Writer, RtDepTime.GetValue());	
	}
	if (RtArrTime.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("rtArrTime")); WriteJsonValue(Writer, RtArrTime.GetValue());	
	}
	Writer->WriteIdentifierPrefix(TEXT("name")); WriteJsonValue(Writer, Name);
	if (ArrTime.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("arrTime")); WriteJsonValue(Writer, ArrTime.GetValue());	
	}
	Writer->WriteIdentifierPrefix(TEXT("lat")); WriteJsonValue(Writer, Lat);
	if (RtDepDate.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("rtDepDate")); WriteJsonValue(Writer, RtDepDate.GetValue());	
	}
	if (RtArrDate.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("rtArrDate")); WriteJsonValue(Writer, RtArrDate.GetValue());	
	}
	Writer->WriteObjectEnd();
}

bool SwaggerStop::FromJson(const TSharedPtr<FJsonObject>& JsonObject)
{
	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("routeIdx"), RouteIdx);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("arrDate"), ArrDate);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("depTime"), DepTime);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("lon"), Lon);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("depDate"), DepDate);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("track"), Track);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("rtTrack"), RtTrack);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("id"), Id);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("rtDepTime"), RtDepTime);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("rtArrTime"), RtArrTime);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("name"), Name);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("arrTime"), ArrTime);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("lat"), Lat);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("rtDepDate"), RtDepDate);
	ParseSuccess &= TryGetJsonValue(JsonObject, TEXT("rtArrDate"), RtArrDate);

	return ParseSuccess;
}
}
