/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
#include "VasttrafikModule.h"

IMPLEMENT_GAME_MODULE(FDefaultGameModuleImpl, VastTrafik)
DEFINE_LOG_CATEGORY(LogSwagger);
