/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
using System;
using System.IO;
using UnrealBuildTool;

public class Vasttrafik : ModuleRules
{
    public Vasttrafik(ReadOnlyTargetRules Target) : base(Target)
    {
        PublicDependencyModuleNames.AddRange(
            new string[]
            {
                "Core",
                "CoreUObject", "Engine",
                "Http",
                "Json",
                "JsonUtilities",
                "GeometryCore", 
                "GeoReferencing",
                "DigitalTwin",
            }
        );
    }
}